### ISSUE TITLE
Missing chapter of OIDC Authentication REST API

### ISSUE THREAD

**Issue by InbalZilberman** [cyberark/conjur#1044]
The chapter of "OIDC Authentication REST API" is missing from online help both in OSS and DAP

**Comment by shuligh** [comment]
@InbalZilberman weI don't have a REST API topic.
Did we have it in the PDF?

**Comment by InbalZilberman** [comment]
yes we did attaching the pdf
[https://app.zenhub.com/files/62174977/3fb391b0-5e34-4a8e-92e3-e836de6a8f39/download](https://app.zenhub.com/files/62174977/3fb391b0-5e34-4a8e-92e3-e836de6a8f39/download)

**Comment by InbalZilberman** [comment]
opened in the wrong repo
