### ISSUE TITLE
differences between OSS and DAP in OIDC

### ISSUE THREAD

**Issue by InbalZilberman** [cyberark/conjur#1046]
1. In step 5 of the the configuration of OIDC there is a difference between OSS and DAP
2. in many places we say Conjur appliance in OSS docs it should be Conjur server

**Comment by InbalZilberman** [comment]
Wrong repo :https://app.zenhub.com/workspaces/onlyconjurdocs-5cf7a9ea1b8cc8533860c99c/issues/cyberark/conjur-docs/276

**Comment by shuligh** [comment]
fixed

**Comment by InbalZilberman** [comment]
@shuligh @yserota I cant find OIDC in OSS documentation hence cant review this ticket. 
Please move this again to review once fixed.
