### ISSUE TITLE
Conjur should return a usable as-is access token

### ISSUE THREAD

**Issue by orenbm** [cyberark/conjur#1050]
At this point, Conjur returns an access token that users/hosts need to base64 encode it before they can use it in API calls. We should improve the ux of this.

there is a slack thread here: https://conjurhq.slack.com/archives/C0A2NF134/p1557841105256800

**Comment by orenbm** [comment]
@liavyona can this issue be closed? if so, please link to the PR in a comment a close.

**Comment by izgeri** [comment]
is the solution design in #1740 going to be merged as well?

**Comment by orenbm** [comment]
@liavyona this can be closed, correct?
