### ISSUE TITLE
Audit events are present for user or host authentication

### ISSUE THREAD

**Issue by jvanderhoof** [cyberark/conjur#1055]
As a security administrator, I want to know when user or host successfully or unsuccessfully authenticates with Conjur, so that I can detect any suspicious behavior.

GIVEN a running Conjur instance with a user
WHEN a user or host authenticates with a valid username/hostname and invalid API key
THEN an audit message is present in the audit log noting the unsuccessful authentication attempt 
AND WHEN that user or host authenticates with a valid username/hostname and invalid API key
THEN an audit message is present in the audit log noting the successful authentication

## Developer Notes
- Audit message should conform to our audit format

**Comment by h-artzi** [comment]
The following [Uploading Invalid_API_Key.mov.zip…](video) shows the audit logs on the Conjur-UI. The steps completed were all done with a valid username.

1. Call `conjur list` with incorrect API Key via CLI
2. Call `conjur list` with incorrect API Key via CLI
3. Call `conjur list` with correct API key via CLI
4. Call `conjur list` with incorrect API key via CLI
5. Login via the UI
6. Find the instance where it prints invalid credentials, invalid credentials, success, invalid credentials

Is this the result we were interested in? @jvanderhoof

**Comment by micahlee** [comment]
I agree that this story is satisfied in the existing product.
