### ISSUE TITLE
Errors return HTML rather than JSON for 500 errors

### ISSUE THREAD

**Issue by jvanderhoof** [cyberark/conjur#1068]
## Issue description
On error, requests made through the API return an HTML rather than an HTML error

## Steps to reproduce the issue
1. <steps-to-reproduce> 

## What's the expected result?
- <expected result>

## What's the actual result?
- <actual result>

## Additional details / screenshot

- ![Screenshot]()
-

**Comment by sjacobs146** [comment]
This bug is almost 2 years old. Closing
