### ISSUE TITLE
Kubernetes Authenticator fails on nested layers

### ISSUE THREAD

**Issue by jvanderhoof** [cyberark/conjur#1071]
## Issue description
When the authenticator webservice is nested, hosts cannot authenticate.

## Steps to reproduce the issue
1. <steps-to-reproduce> 

## What's the expected result?
- <expected result>

## What's the actual result?
- <actual result>

## Additional details / screenshot

- ![Screenshot]()
-

**Comment by sjacobs146** [comment]
This bug is almost 2 years old. Closing
