### ISSUE TITLE
`authn` is disabled if it is not in the env

### ISSUE THREAD

**Issue by orenbm** [cyberark/conjur#1076]
We say in our docs that `When the environment variable CONJUR_AUTHENTICATORS is set, then only the authenticators listed are whitelisted. This means that the Conjur authenticator authn must be included in the list. If CONJUR_AUTHENTICATORS is set and authn is not in the list, default Conjur authentication is not available.`

This is not the actual behaviour as even if `authn` is not in the env we can still use it to authenticate.

We need to decide what the wanted behaviour is and fix the implementation or the documentation.

**Comment by orenbm** [comment]
@alexkalish @InbalZilberman what is the behaviour that we want in this case?

If the `CONJUR_AUTHENTICATORS` env var doesn't include `authn`, should we still accept authn requests? Our docs say that we shouldn't but our code accepts such requests.

**Comment by orenbm** [comment]
@alexkalish @InbalZilberman ^

**Comment by eladkug** [comment]
@InbalZilberman please open ticket for conjur-docs

**Comment by eladkug** [comment]
duplicate to [1058](https://app.zenhub.com/workspaces/palmtree-5d99d900491c060001c85cba/issues/cyberark/conjur-docs/1058)
