### ISSUE TITLE
Modify log level with specific env var instead of RAILS_ENV

### ISSUE THREAD

**Issue by orenbm** [cyberark/conjur#1098]
We should have the ability to configure the log level with a separate environment variable other than RAILS_ENV. changing the latter to development has side effects other than changing the log level to debug and we should avoid changing that for this purpose.

Changes should be in:
- evoke
  - change `LOG_LEVEL` to `CONJUR_LOG_LEVEL` to be the variable in `conjur.conf`
  - change default level to `warn`?
- possum
  - set default value to `info/warn`
  - consume `ENV['CONJUR_LOG_LEVEL']` in all environment files and set default values in case they don't show
- appliance
  - fix the cucumber step that enables debug level

**Comment by jtuttle** [comment]
@orenbm Can we close this?

**Comment by orenbm** [comment]
sure, thanks!
