### ISSUE TITLE
(Beta) Can k8s secrets be defined in the deployment config under the app container 

### ISSUE THREAD

**Issue by nessiLahav** [cyberark/conjur#1122]
Look at the option 1 under (Expected process logic) in feature doc  https://ca-il-confluence.il.cyber-ark.com/display/rndp/Spike+-+How+authn-client+receives+K8s+secrets#/

DoD:
Investigate if the authenticator can identify which k8s secrets data (conjur paths) to fetch according the app container configuration in deployment config (as suggestion above).
implement this action from authenticator code inside OpenShift

**Comment by sigalsax** [comment]
CONSENSUS:
We will start implementing the Option #2 (Authn-client reading a comma separated secrets list in config file to understand the secrets the pod needs (simple design)) and if time allots, will upgrade to Option #1 (Authn-client reading Pod data using the K8s API endpoint (more complex design))
