### ISSUE TITLE
(GA) Make cyberark-secrets-provider-for-k8s as public repo

### ISSUE THREAD

**Issue by nessiLahav** [cyberark/conjur#1185]
DO NOT MERGE

requirements for making repos public: https://github.com/conjurinc/docs/blob/master/reference/open_source/public_repos.md

**Comment by sigalsax** [comment]
To make a repo public we need to follow the following:
- [ ] Ask both Geri + Brian and post in ConjurHQ Slack in #about-oss 
Have the following ready before posting in channel
- [ ] A license (Apache 2.0 for demos and client libraries)
- [ ] A README must be provided
    1. Release checklist must be reviewed to ensure we have met the requirements for each release and this should be described in the README
https://github.com/conjurinc/docs/blob/master/reference/release_checklist.md
    2. README should be in the format according to what is described here: https://github.com/conjurinc/docs/blob/master/reference/public_repos.md#is-there-a-helpful-readme-and-project-description
    2. Link back to entrypoint page for OSS (https://github.com/cyberark/)
    3. Indicate which versions of our software and tools our project supports based on our testings
    4. README should include release state 
    5. It must be decided who will maintain the repo (and have a list of others to cover them if on vacation/leave)
        1. Maintainers watch for damages PRs or issues
        2. Maintainers will receive alters from GH on discovered vulnerabilities from 3rd party libraries that are in repo.
- [ ] A *CONTRIBUTING.md* should be included. _Suggestion:_ I would mimic secretless’s format https://github.com/cyberark/secretless-broker/blob/latest/CONTRIBUTING.md
    1. How to contribute? What is the workflow? Style guide? Instructions for building/testing
    2. Should include links to CLA documents for contributors to sign before contributing
- [ ] The repo must be scanned with gitleaks or git-secrets
- [ ]. The project must be reviewed to ensure we don’t write any sensitive data to logs or anywhere else (Kumbi?)

**Comment by sigalsax** [comment]
Open questions:
1. This project needs a URL. Is the URL just the GH URL?
2. How to add maintainers to project to get GH updates regarding 3rd party vulnerabilities?
3. Do we need an acknowledgement page? @InbalZilberman 
4. What versions of Conjur does this project support? Kubernetes? K8s secrets? @InbalZilberman

**Comment by sigalsax** [comment]
@hughsaunders noted:
> pre-push scan only checks commits that have changed, when preparing to open source a repo, a full history scan should be run to check there are no credentials buried in the history
command: `gitleaks --repo-path . --config .gitleaks.toml`

Adding this check to the list of requirements above
