### ISSUE TITLE
Repeat Manual test according to docs

### ISSUE THREAD

**Issue by moticless** [cyberark/conjur#1201]
Inbal have found something critical that was not documented. We need to perform again the  manual tests according to the documentation.

docs available at:
https://docs-staging.conjur.org/Push-k8s-secrets-CA/Content/Integrations/Kubernetes_deployApplicationsConjur-k8s-Secrets.htm

**Comment by Tovli** [comment]
The policy that defines the DAP host is loaded into "authn-k8s-{namespace}" but the authentication policy creates a conjur/authn-k8s/{namespace} policy

**Comment by Tovli** [comment]
The policy that defines the DAP host is loaded into "authn-k8s-{namespace}" but the authentication policy creates a conjur/authn-k8s/{namespace} policy

The list of variables is missing the CONJUR_APPLIANCE_URL variable

**Comment by Tovli** [comment]
In the role binding example - "conjur-cluster" should be <follower service account name>

**Comment by Tovli** [comment]
wrong bookmark in "enable debug" link
