### ISSUE TITLE
"account" word duplicated in "Created new account" confirmation message

### ISSUE THREAD

**Issue by infamousjoeg** [cyberark/conjur#1202]
## Steps to reproduce the issue
1. `docker-compose exec conjur conjurctl account create myConjurAccount > admin_data`

## What's the expected result?
- `Created new account 'myConjurAccount'`

## What's the actual result?
- `Created new account account 'myConjurAccount'`

**Comment by izgeri** [comment]
adding in the conjur log output from running through the [quick start](https://www.conjur.org/get-started/quick-start/oss-environment/):
```
[centos@ip-10-0-30-189 conjur-quickstart]$ cat admin_data
Created new account account 'cyberarkdemo'
Token-Signing Public Key: -----BEGIN PUBLIC KEY-----
[redacted]
-----END PUBLIC KEY-----
API key for admin: [redacted]
```
