### ISSUE TITLE
log Authentication errors at "warn" level instead of current "debug" level

### ISSUE THREAD

**Issue by jodyhuntatx** [cyberark/conjur#1224]
As a Developer, I want to know why a Follower is not authenticating my application, so that I can address the issue without a lot of trial & error.

GIVEN an application deployed in K8s/OCP with the authenticator client
WHEN the the Follower rejects the authn request
THEN post the error message such that it is visible in the Follower log at the default log level.

## Developer Notes
In /opt/conjur/possum/app/controllers/authenticate_controller.rb, change "logger.debug" to "logger.warn" at line 104

Repo reference: https://github.com/cyberark/conjur/blob/master/app/controllers/authenticate_controller.rb#L104

**Comment by whip113** [comment]
Looks like this line has moved to line 143 now.

**Comment by InbalZilberman** [comment]
This was fixed in https://github.com/cyberark/conjur/issues/1377 and https://github.com/cyberark/conjur/commit/623f3c3f637a83fcad74a07bbefbb21bbe43ac05
The log is now with INFO log level
