### ISSUE TITLE
Conjur Kubernetes authenticator allows app hosts to be defined in any directory

### ISSUE THREAD

**Issue by orenbm** [cyberark/conjur#1239]
The authn-k8s authenticator requires the applications to be specifically defined under the policy `conjur/authn-k8s/<service_id>/apps`. This behavior does not align with the other authenticator types and is somewhat limiting the control for the user (Further description of the problem is available in #1189).

In other words, instead of limiting all our k8s hosts to the path `host/conjur/authn-k8s/${AUTHENTICATOR_ID}/apps` it would be nice to be able to map to different hosts to different policies. Such as mapping all jenkins hosts to the new path: `host/jenkins_apps/${TEST_APP_NAMESPACE_NAME}/*/*`.

As the design and implementation has finished, we need to get approval for this and merge all relevant PRs.

DoD
- [ ] [Solution design](https://ca-il-confluence.il.cyber-ark.com/pages/viewpage.action?pageId=300391086#/) is reviewed by @jvanderhoof and @alexkalish 
  - Please fill out the table at the end of the doc
- [ ] DoD in the solution design in complete
- [ ] All dependencies have been merged
  - [ ] https://github.com/cyberark/conjur-docs/issues/614
  - [x] https://github.com/cyberark/conjur/pull/1228
  - [ ] https://github.com/cyberark/conjur-authn-k8s-client/pull/59
  - [ ] https://github.com/conjurdemos/kubernetes-conjur-demo/pull/80
  - [ ] https://github.com/cyberark/secrets-provider-for-k8s/pull/47

**Comment by izgeri** [comment]
@orenbm if this is the canonical issue for this change, can you please add more detail to the issue description to describe what this is about? also, it should have the labels `kind/X` and `component/conjur` and would more clearly be named something like `Conjur Kubernetes authenticator allows app hosts to be defined in any directory`

**Comment by orenbm** [comment]
thanks for the input @izgeri, i've done your suggestions.

**Comment by izgeri** [comment]
@orenbm if this is closed, are all of the items in the AC complete as well? it would be nice to check off the items from the description that are complete

**Comment by orenbm** [comment]
thanks @izgeri :)

**Comment by izgeri** [comment]
Thank YOU @orenbm :1st_place_medal:
