### ISSUE TITLE
Annotation (Part 1 - Design/Implementation)

### ISSUE THREAD

**Issue by Tovli** [cyberark/conjur#1241]
This task will be dividing into two across 2 sprints and is the first card in a two-part series.

Part 1:
- [ ] Design doc solution with test plan solution
- [ ] Design doc has been reviewed
- [ ] Security Review
- [ ] Implementation

Part 2 (Implement Test Plan)
https://app.zenhub.com/workspaces/palmtree-5d99d900491c060001c85cba/issues/cyberark/conjur/1246

**Comment by sigalsax** [comment]
Estimate:
- Research (3 days) including how to DEBUG
- Test Plan (3 days), build test plan, see how other tests are structured (unit tests AND integration?)
- Security review (dependent on current load on Shahar)
- Implementation (2 or 3 days depending on measures that are currently in place)
- Security guidelines on how to approach DAP NG (1.5 days)

**Comment by sigalsax** [comment]
moved to AAM repo so closing here
