### ISSUE TITLE
authn-k8s loads the whole cert chain to the cert store

### ISSUE THREAD

**Issue by orenbm** [cyberark/conjur#1247]
When we create the k8s client to investigate k8s resources, we create a cert store that contains the CA cert. We do so by running `OpenSSL::X509::Store.new.add_cert(ca_cert)` where `ca_cert` contains the cert chain.

Apparently, `add_cert` [adds only the intermediate certificate](https://jira.mongodb.org/browse/RUBY-1774) so we will have an SSL error in case the chain includes more that one certificate in the chain.

In OCP 3 that is the case - we have only 1 certificate in the chain and this "the first certificate" == "all the certificates in the chain". In OCP 4 there is more than 1 certificate in the chain so we need to load the CA cert in another way.

We have a solution for this in our Ruby API which we can take. Usage can be found [here](https://github.com/cyberark/conjur-api-ruby/blob/0e7d0d4c8c90a963370dd4efef05a983f996458c/lib/conjur/configuration.rb#L405-L414) and [here](https://github.com/cyberark/conjur-api-ruby/blob/0e7d0d4c8c90a963370dd4efef05a983f996458c/lib/conjur/cert_utils.rb)

**Comment by izgeri** [comment]
This was released in [v1.4.4](https://github.com/cyberark/conjur/releases/tag/v1.4.4)
