### ISSUE TITLE
Conjur quick start not pulling latest Conjur version

### ISSUE THREAD

**Issue by sigalsax** [cyberark/conjur#1253]
The conjur quick-start (the way we have our users spin up conjur env) doesn't have the latest additions from Conjur (the Conjur logs) and therefore, the formatting is not correct. Which means we might have a bug in configuration for quick-start in that it isn't pulling the latest version of Conjur. 
Quick-start logs:
`[ORIGIN] [REQUEST ID] [THREAD ID] [MSG]`

Ex:
`[origin=172.29.0.3] [request_id=438d77c9-6c82-42c2-9620-589275dc28cc] [tid=34] Authentication Error: #<Errors::Authentication::InvalidCredentials: CONJ00002E Invalid credentials>`

And from the Conjur repo, the logs look like
`[SEVERITY] [TIMESTAMP] [PROCESS ID] [ORIGIN] [REQUEST ID] [THREAD ID] [MSG]`
Ex:
`INFO 2020/01/05 14:16:00 +0000 [pid=373] [origin=172.24.0.1] [request_id=47dcf956-1481-4256-a972-7b08d3a5b91c] [tid=383] Completed 401 Unauthorized in 68ms`

So we need to find out why this is happening and make a fix for this in the conjur quick-start. If we choose to not fix this bug, we will need to update the OSS log doc to be how the quick-start

**Comment by izgeri** [comment]
@sigalsax should this issue be logged in github.com/cyberark/conjur-quickstart?

**Comment by sigalsax** [comment]
yes you are right- I couldn't find the repo for some reason. Moving it over now!

**Comment by sigalsax** [comment]
closing and opened new issue here: https://github.com/cyberark/conjur-quickstart/issues/8
