### ISSUE TITLE
Policy with multiple members on groups should add all of them or fail

### ISSUE THREAD

**Issue by orenbm** [cyberark/conjur#1263]
Connected to #1262

---
## Issue description

In case we load a policy with a group that has more than 1 member, only the last one will be loaded.

## Steps to reproduce the issue

Load the following policy:
```
- !host host1
- !host host2

- !variable secret
- !group secret-consumers

- !permit
  role: !group secret-consumers
  resource: !variable secret
  privilege: [ read, execute ]

- !grant
  role: !group secret-consumers
  member: !host host1
  member: !host host2
```

## What's the expected result?

One of the following:
1. The group `secret-consumers` Includes all the members.
2. Policy load fails as it has 2 `member` clauses for `grant`. 

## What's the actual result?

Policy load succeeds and the group `secret-consumers` includes only `host2`

**Comment by oburstein-hub** [comment]
Fixed by adding verification for multiple entries with the same name
