### ISSUE TITLE
Conjur server status page links to Slack that no longer exists

### ISSUE THREAD

**Issue by izgeri** [cyberark/conjur#1341]
## Steps to reproduce the issue
1. Run the [quick start](https://www.conjur.org/get-started/quick-start/oss-environment/)
1. Navigate to https://localhost:8443

## What's the expected result?
- Conjur Server status page has link to [discourse](https://discuss.cyberarkcommons.org)

## What's the actual result?
- Conjur Server status page has link to old public slack

## Additional details / screenshot
<img width="1170" alt="Screen Shot 2020-02-18 at 9 02 30 PM" src="https://user-images.githubusercontent.com/26872683/74794735-045b0c00-5292-11ea-8734-6a785413e6b3.png">

**Comment by h-artzi** [comment]
This seems to already be fixed.![Screen Shot 2020-03-18 at 11.40.55 AM.png](https://images.zenhubusercontent.com/5e2f48a012ff850fd79f8370/729b4696-649a-4873-90df-d436d60bd46d)

**Comment by izgeri** [comment]
I fixed it in #1342 - I'm not sure why the issue is still open? maybe it was waiting for a new tag, but it's included in v1.4.7 now so I think this issue can be closed
