### ISSUE TITLE
Log authentication and login failures at the `info` level, rather than `debug`

### ISSUE THREAD

**Issue by micahlee** [cyberark/conjur#1377]
The generic `401` error response from authenticators (specifically `authn-k8s`) can have a variety of root causes, some of them not directly related to the authentication credentials themselves, but rather issues with the authenticator configuration.

Currently the way to gather more information for a authentication failures is to increase the log level for Conjur to `debug`. However, this also turns on logging of all database queries, and because the rotator process executes a SQL query every second for pending rotations, this makes it very difficult to find the information you're looking for.

The proposal to improve this experience is to log authentication failures at the `info` log level, rather than `debug`.

**Comment by micahlee** [comment]
Blocked by #1464

**Comment by orenbm** [comment]
Unblocked by #1464 as we found no issue in logging these messages in INFO level
