### ISSUE TITLE
Kubernetes required variables for seedfetcher or out-of-cluster Followers lack of checks

### ISSUE THREAD

**Issue by alexkalish** [cyberark/conjur#1394]
Request from the field:
> When using seed-fetcher, the `conjur/auth-k8s/authenticator-ID/Kubernetes/api-url variable` should not end with a “/” – can checks be added when setting variable?

Suggestion from @jvanderhoof:
> Let's make the authenticator more flexible so it can better handle the URLs

**Comment by h-artzi** [comment]
Attempted to recreate the issue, however, was unable to: 

the API URL: 
`root@conjur-cli-69ddbb9785-qn256:/# conjur variable value conjur/authn-k8s/dev/kubernetes/api-url && echo https://openshift-311.itci.conjur.net:8443/`<br>

the follower connected to the master and ran successfully. 
<pre>`~/work/../dev (ruby-2.6.1) $ kcp`
`NAME                           READY     STATUS    RESTARTS   AGE`
`dap-follower-8cc7c5949-8t5pc   5/5       Running   0          2m`</pre>

Which seedfetcher is being used? 
Is there any more context that can be provided?

**Comment by jvanderhoof** [comment]
@alexkalish, any thoughts on how we might continue to move this forward?  Do you know if the user was using the latest version of the seed fetcher?
