### ISSUE TITLE
Disable MD5 in Rails

### ISSUE THREAD

**Issue by alexkalish** [cyberark/conjur#1418]
Part of the motivation for upgrading Rails to 5.2 is to ensure FIPS support for the Fed project.  This also requires that we disable all use of MD5, which is not FIPS supported.  There is a simple config option that we need to set in order to make this change:

```
Rails.application.config.active_support.use_sha1_digests = true
```

See related [SO post](https://stackoverflow.com/questions/36577563/rails-4-2-6-disable-md5-for-fips-compliance).

**Comment by jonahx** [comment]
Should this also have been close when we merged the change?
