### ISSUE TITLE
Conjur Status page does not display the correct version

### ISSUE THREAD

**Issue by jvanderhoof** [cyberark/conjur#1438]
## Issue description
When a new Conjur instance is started, it shows the version as `5.0`.

## Steps to reproduce the issue
1. Run the [quick start](https://www.conjur.org/get-started/quick-start/oss-environment/)
1. Navigate to https://localhost:8443

## What's the expected result?
- Version should match the latest released version (currently `v1.4.7`)

## What's the actual result?
- Version is `5.0`

## Additional details / screenshot

![Screen Shot 2020-03-17 at 11 58 41 AM](https://user-images.githubusercontent.com/124978/76908721-01dada80-686f-11ea-9c0c-691debb73334.png)

**Comment by izgeri** [comment]
Just noting this is the new page:
<img width="1344" alt="Screen Shot 2020-10-28 at 5 14 41 PM" src="https://user-images.githubusercontent.com/26872683/97497579-1b81eb80-1941-11eb-90bf-45027aab5fb1.png">
