### ISSUE TITLE
A new version of Conjur is released

### ISSUE THREAD

**Issue by jvanderhoof** [cyberark/conjur#1493]
Please complete the following tasks to release this project.

- [ ] Check `master` branch build is currently green (fix if it is not).
- [ ] Pull all remote changes locally (`git pull --rebase origin`).
- [ ] Review the scope of changes to understand the version new version ([Semver Summary](https://semver.org/#summary))
- [ ] Increment the `VERSION` file to the desire release number.
- [ ] Create a release branch (ex. `git checkout -b v1.2.3`) with the desired release number.
- [ ] Review commits to insure all relevant changes have Changelog entries.
- [ ] Review the `Gemfile.lock` history and update `NOTICES.txt` with any library changes.
- [ ] Review `CHANGELOG.md` to:
  - [ ] Move `Unreleased` changes to the release number.
  - [ ] Refactor changes to confirm to the [Keep a Changelog Standard](https://keepachangelog.com/en/1.0.0/#how).
- [ ] Open a Pull Request, tagging relevant teammates.
- [ ] Upon approval and successful build, merge using "Squash and merge".
- [ ] Tag the release (`git tag -a v1.2.3 -m "v1.2.3 release"` and `git push origin v1.2.3`).
- [ ] Wait for successful build.
- [ ] Add the Jenkins artifact name as a comment to this task.

**Comment by jonahx** [comment]
conjur-possum_1.6.0-1420681_amd64.deb
