### ISSUE TITLE
Update reference to the short form -j of the --jenkins flag

### ISSUE THREAD

**Issue by jonahx** [cyberark/conjur#1506]
As part of the Rails 5 upgrade, we removed the short form `-j` of the `--jenkins` flag for the `build.sh` script, but one stray reference was not updated. 

We think this may be related to the CI slowness the Rails 5 upgrade introduced.

**Comment by jonahx** [comment]
@jvanderhoof This should have been close with that merge I believe.  Any reason it wasn't?

**Comment by orenbm** [comment]
@jonahx out of curiosity, why did we make this change? did we have an issue with `-j` in Rails 5?

**Comment by jonahx** [comment]
@orenbm No, there was just no reason ever to have it.  Short form flags are only useful for command line typing, to save keystrokes.  This flag was only ever meant to be used in scripts, where we should always use the long-form so the purpose of the flag is clear at the calling site.

**Comment by orenbm** [comment]
@jonahx can we close this issue? i can't find any `-j` in our code? Or am i missing something?

**Comment by jonahx** [comment]
I want to say there was some problem recently with another project (like evoke or something) that was making reference to the `-j` flag instead of the `--jenkins` flag.  But I'm assuming that's been fixed?

**Comment by orenbm** [comment]
I can't find a reference to this so this issue doesn't have any action item. Closing it.

**Comment by jonahx** [comment]
cc/ @micahlee @jtuttle ☝️ (my last comment)
