### ISSUE TITLE
Validate an API generated key continues to work after upgrade

### ISSUE THREAD

**Issue by jvanderhoof** [cyberark/conjur#1513]
There are some concerns that the change from [sha 1 digests](https://github.com/cyberark/conjur/commit/8581b57c343feffe5861699de68cd6017bf9fb69#diff-b1fe55db50c712fef0673345e5b9c0d9) may cause some unintended issues for upgrades.  To manage this risk, please:

1. Perform a dap upgrade and verify API works after the upgrade <sup>1</sup>.
2. Spend 2 hours reviewing possible breaks that could result from the change from MD5 to SHA1.

**Dev Notes**
I'd recommend we modify [DAP Intro](https://github.com/conjurdemos/dap-intro)  to include a demo that runs a user through an upgrade process.  An upgrade looks like the following:

1. Start a DAP appliance of a particular version with a backup volume mounted to the local file system.
1. Configure DAP
1. Login into the UI with the admin password
1. Load a policy with a host through the CLI
1. Verify the host can authenticate using the generated API key
1. Perform a backup (using the mounted backup volume to insure the backup survives stopping the container).
1. Stop the original DAP 
1. Start a DAP appliance (the latest version)
1. Restore DAP from the backup
1. Verify the admin can log into the UI
1. Verify the host can authenticate with the API key

**Comment by jonahx** [comment]
> 1. Confirmation that the process was followed exactly as described above.  Or if there were changes, please list them.

Yes, all steps were followed exactly as above.

> 2. A very brief explanation about how (if at all) the Rails internal hash algorithm affects generation of new API keys and the verification of existing ones.

The API keys are unaffected by the Hash algorithm.  It's easy to verify this by looking at the code that generates them in `app/models/credentials.rb`:

```
  class << self
    def random_api_key
      require 'base32/crockford'
      Slosilo::Random.salt.unpack("N*").map{|i| Base32::Crockford::encode(i)}.join.downcase
    end
  end
```

> 3. A brief explanation of the additional investigation steps taken to confirm there aren’t other obvious issues caused by this hash algorithm change.

Manual code inspection.  The only step not performed was a full investigation of the Rails source code, finding every place that uses digests, and then cross referencing with every function call made in our app.  I think this would be overkill.

**Comment by andytinkham** [comment]
@jonahx and I spoke today with @eladkug and @CyberGada. They confirmed that the above task satisfied their concerns.

**Comment by sjacobs146** [comment]
As per @andytinkham 's comments, it appears that this can be closed.
