### ISSUE TITLE
All Conjur test results are captured in a Jenkins build

### ISSUE THREAD

**Issue by jvanderhoof** [cyberark/conjur#1515]
Not all the test results are visible in the build test report (example from [build 1191](https://jenkins.conjur.net/job/cyberark--conjur/job/master/1191/testReport/). This makes it harder for engineers to identify why a build failed. It also prevents us from identifying flapping tests.

Please validate that all test results from the [Conjur tests](https://github.com/cyberark/conjur/blob/master/Jenkinsfile#L68) are present in the test report. The easiest way to do this is to verify a test from stage appears in the results file.  [View the test results from a particular build in JSON form](https://jenkins.conjur.net/job/cyberark--conjur/job/master/1191/testReport/api/json?pretty=true&tree=suites[cases[className,name]]).

**Comment by eladkug** [comment]
Under cucumber reports i can see all the [test results](https://jenkins.conjur.net/job/cyberark--conjur/job/master/1191/cucumber-html-reports/overview-features.html)

Looks like only api and policy tests is visible [here](https://jenkins.conjur.net/job/cyberark--conjur/job/master/1191/testReport/api/json?pretty=true&tree=suites%5Bcases%5BclassName,name%5D%5D) and all the rest are unit test.
i will take it from here.
