### ISSUE TITLE
Conjur has clear upgrade instructions

### ISSUE THREAD

**Issue by izgeri** [cyberark/conjur#1528]
If I am using Conjur, and a new version becomes available, I want to be able to seamlessly upgrade my current version of Conjur to the new version without losing any data and with minimal downtime.

## Additional context

It may be that certain versions of Conjur require special upgrade instructions; this card is not meant to capture that. The output of this card should be _standard_ upgrade instructions that typically apply / represent a baseline for Conjur operation. Given these baseline upgrade instructions (which should account for updating the Conjur server, performing any needed database migrations, and any other standard upgrade operations) should enable us to provide documentation on exceptions to this standard that arise for any given Conjur version bump.

**Comment by uCatu** [comment]
Following steps were performed to upgarde from OSS v.{x} to OSS v.{x+1}:
1. Edit `docker-compose.yml` conjur service image tag to {x+1}
2. Delete current conjur container: 
`docker rm -f conjur`
3. Rerun docker-compose:
`docker-compose up -d`
4. View docker contaiers and verify all are healthy, up and running:
 'docker ps -a`

* side note, it is possible you will need to reassigne `CONJUR_DATA_KEY` system varaible. Same key as before. 
`export CONJUR_DATA_KEY="$(< data_key)`

**Comment by izgeri** [comment]
@uCatu I vaguely remember someone mentioning an operation with slosilo was needed - did you have to do something like this at any point? Also, do you know what might be different about these instructions if there is a database migration between versions?

**Comment by shulifink** [comment]
@izgeri  - is this ticket also meant to cover High availability and autofailover upgrade for DAP?

**Comment by izgeri** [comment]
@shulifink not at all - this ticket is _just_ for standard upgrade instructions that can be used to migrate one docker-compose deployment of Conjur OSS to a newer version of Conjur

**Comment by izgeri** [comment]
This is resolved in #1607. See [UPGRADING.md](UPGRADING.md) for more info.
