### ISSUE TITLE
Kubernetes authenticator `inject_client_cert` produces audit record on failure

### ISSUE THREAD

**Issue by micahlee** [cyberark/conjur#1538]
## Overview
When the `authn-k8s` `/inject_client_cert` endpoint fails, it should produce an authentication failed audit event including the failure information.

Currently, the only way to determine the reason for certificate injection failure is to enable `DEBUG` logging on the Conjur server and view the stack trace in the server logs. This is also different from the the `/authenticate` endpoint, which does include initial failure information in the audit log.

This is an alternative to logging the top-line error information at the `WARN` level, and better protects audit failure reasons from leaking any authentication information, since audit records are protected by RBAC.

## Technical Notes

Consider the `authenticate/` error handling, where all failure causes are audit logged before returning the error to the end user as a generic `401 Unauthorized`:
https://github.com/cyberark/conjur/blob/12494b3ae5838c28b5a5a15699f8e8f5fa2475d1/app/domain/authentication/authenticate.rb#L22-L32

In contrast, `inject_client_cert` only returns the `401` without logging the failure in the audit records:
https://github.com/cyberark/conjur/blob/12494b3ae5838c28b5a5a15699f8e8f5fa2475d1/app/controllers/authenticate_controller.rb#L110-L123

https://github.com/cyberark/conjur/blob/12494b3ae5838c28b5a5a15699f8e8f5fa2475d1/app/domain/authentication/authn_k8s/inject_client_cert.rb#L22-L26

**Comment by micahlee** [comment]
@orenbm @andytinkham @shaharglazner @alexkalish @AndrewCopeland @jtuttle 

I'd love to get your take on this proposal to add audit authentication logging to the `inject_client_cert` endpoint of the Kubernetes authenticator.

In my mind, this would be a shift in direction from [logging more information in the Conjur server logs](https://github.com/cyberark/conjur/issues/1377), to making more of this kind of information in the audit log instead.

**Comment by orenbm** [comment]
I think that regardless to the fact that it's hard to get the error from the logs (which can be tackled in another approach), it makes sense to add an audit message for `inject_client_cert` as a Conjur user/host performs an access request to Conjur. So I'll +1 for this issue.

**Comment by andytinkham** [comment]
I agree - I think that it makes sense to include an audit log message. Injecting client certs could potentially open a number of different attacks, and having audit log warnings that someone was trying to get a client cert into the system seems like a good thing. I'm not sure what you're intending that log message to actually say - there's some variants there that would be leaking info, of course - but the idea itself seems sound to me.
