### ISSUE TITLE
API responses set content-type correctly

### ISSUE THREAD

**Issue by alexkalish** [cyberark/conjur#1544]
## Summary

According to our API docs, some of our endpoints apparently return the wrong content-type (or at least a less precise/appropriate one).  This is unlikely a big deal with API clients, as we haven't received any complaints (at least as far as I know).  Nonetheless, we should correct this.

Example: the [rotate API key endpoints docs](https://docs.cyberark.com/Product-Doc/OnlineHelp/AAM-DAP/Latest/en/Content/Developer/Conjur_API_Rotate_Personal_API_Key.htm?tocpath=Developer%7CREST%C2%A0APIs%7C_____4) state that we return `text/html`, but looking at the response body, it's really just plain text.  So, the response content type should be `text/plain`.

<img width="624" alt="image" src="https://user-image* s.githubusercontent.com/226777/82062713-83e15700-9698-11ea-9e2c-628801142cf2.png">

## Definition of Done

* [x] Review all API docs and build a list of APIs with response content to content-type mismatches.  If the docs do not include a content-type, check the code.
 &#x2612; Confirm that the docs are correct that these APIs return the stated content-types.
* [x] Update the code to return a more appropriate content-type.
* [x] Update tests to verify the response content-type.
* [x] File a docs issue in our private docs.conjur.org docs repo to update these API docs.

**Comment by sjacobs146** [comment]
Assigned to @h-artzi because he's the person who put it in progress state.

**Comment by h-artzi** [comment]
[Response Codes](https://app.zenhub.com/files/62174977/355ed16e-a33f-479a-bd08-38282a9efba3/download)

**Comment by h-artzi** [comment]
| REST API                      | Expected Header                  | Actual Header                                                         |
|-------------------------------|----------------------------------|-----------------------------------------------------------------------|
| login                         | text/html; charset=utf-8         | text/plain                                                            |
| Authenticate                  | Not written                      | Application/json                                                      |
| Change your password          | N/A                              | 204 status code                                                       |
| Rotate Personal API Key       | text/html; charset=utf-8         | Text/plain                                                            |
| Rotate Another Role’s API Key | text/html; charset=utf-8 and 200 | Text/plain when rotating a user’s api key but did not                 |
|                               |                                  | did not find the response when you rotate a host’s api key            |
| Add secret                    | Content-Type:application/xml     | 201 status code and no content                                        |
| Retrieve a secret             | Content-Type:application/json    | resource.annotation('conjur/mime_type') \|\| application/octet-stream |
| Batch retrieval               | Content-Type: application/json   | Content-Type: application/json                                        |
| Replace a policy              | Content-Type:application/json    | Content-Type:application/json                                         |
| Append to a policy            | Content-Type:application/json    | Content-Type:application/json                                         |
| Update a policy               | Content-Type:application/json    | Content-Type:application/json                                         |
| Show a role                   | Content-Type:application/json    | Content-Type:application/json                                         |
| List a Role’s members         | Content-Type:application/json    | Content-Type:application/json                                         |
| List resources                | Content-Type:application/json    | Content-Type:application/json                                         |
| Show a resource               | Content-Type:application/json    | Content-Type:application/json                                         |
| Show permitted roles          | Content-Type:application/json    | Content-Type:application/json                                         |
| Check permission              | N/A                              | 204 status code                                                       |
| Create Tokens                 | Content-Type:application/json    | Content-Type:application/json                                         |
| Revoke Tokens                 | N/A                              | 204 status code                                                       |
| Create a host                 | Content-Type:application/json    | Content-Type:application/json                                         |
| Show Public Keys              | Content-Type: text/plain         | Content-Type: text/plain                                              |
| Health Check                  | Not written                      | Content-Type: application/json                                        |
| OIDC Authenticator            | Not written                      | Content-Type: application/json                                        |
| Azure Authenticator           | Not written                      | Content-Type: application/json                                        |

**Comment by micahlee** [comment]
@h-artzi, what was your method for collecting the `Actual Header` value?

**Comment by micahlee** [comment]
@h-artzi Are any of these different when the response is an error?

**Comment by h-artzi** [comment]
I went through the code base and checked what it was being rendered as. I did not look through all the error codes and their content types. I can add that as a column

**Comment by h-artzi** [comment]
I believe our current documentation does not cover the content type of error codes, instead, it just states the response code. Do you think it is valuable to add the content type of error responses? @micahlee

**Comment by micahlee** [comment]
> I went through the code base and checked what it was being rendered as.

So we're assuming the content type from the `render plain:` or `render json:`?

We probably should make sure that's actually what we're getting from an HTTP client.

> Do you think it is valuable to add the content type of error responses?

Regardless of what ends up in the official docs, we should make an initial effort to understand what an error would return. I don't actually know off-hand if there is content or not with errors, and if so, what kind of content it is.

It would be helpful if errors are always the same, but I'm guessing that may not be the case...

**Comment by h-artzi** [comment]
WIP
Error Codes
401 -> text/html
404 -> application/json 
422 -> application/json, charset=utf-8
403 -> This one has a mix. Either its application/json or has no content

**Comment by h-artzi** [comment]
DOC ISSUE: https://github.com/cyberark/conjur-docs/issues/1022
