### ISSUE TITLE
Changing a Password is audited

### ISSUE THREAD

**Issue by jvanderhoof** [cyberark/conjur#1548]
As a security administrator, I want to know when users attempt to change their passwords so that I can detect any suspicious behavior.

GIVEN a running Conjur instance
WHEN I change my password with an invalid password <sup>1</sup>
THEN I see an unsuccessful password change audit event <sup>2</sup>

AND WHEN I change my password with a valid password <sup>3</sup>
THEN I see a successful password change audit event <sup>4</sup>

**Notes**
Conjur does not currently support changing another user's password. The only way to "fail" when setting a password is to attempt to change a password to something that does not meet the complexity requirements.

---

<sup>1</sup> Change the `admin` user's password to a password that does not meet the complexity requirements:
```sh
$ curl -k -X PUT --data password --user admin:ADmin123!!!! \
http://localhost:3000/authn/cucumber/password
```

<sup>2</sup> Unsuccessful "Change Password" audit event should follow the [Audit Event convention](https://github.com/cyberark/dap-wiki/blob/api-docs/reference-architectures/audit.md). Before we implement, let's get agreement on the format. A possible format could be:
- subject@43868 
    - user: `cucumber:user:admin`
- auth@43868 
    - user: `cucumber:user:admin`
- action@43868 
    - result: `failure`
    - operation: `update` 
- MSGID: password
- MESSAGE: "cucumber:user:admin failed to update password for cucumber:user:admin due to complexity requirements"
- LEVEL: "notice"

<sup>3</sup> Change the `admin` user's password to a password that meets the complexity requirements:
```sh
$ curl -k -X PUT --data ADmin123!!-new --user admin:ADmin123!!!!
http://localhost:3000/authn/cucumber/password
```

<sup>4</sup> Successful "Change Password" audit event should follow the [Audit Event convention](https://github.com/cyberark/dap-wiki/blob/api-docs/reference-architectures/audit.md). Before we implement, let's get agreement on the format. A possible format could be:
- subject@43868
    - user: `cucumber:user:admin`
- auth@43868
    - user: `cucumber:user:admin`
- action@43868
    - result: `success`
    - operation: `update`
- MSGID: password
- MESSAGE: "cucumber:user:admin updated password for cucumber:user:admin"
- LEVEL: "notice"

**Comment by micahlee** [comment]
Possible locations to hook in the audit event:

* In the controller:
 https://github.com/cyberark/conjur/blob/3df4a7c86d14ddf85eed982efa74f953f3de88fd/app/controllers/credentials_controller.rb#L36-L42

* In the model using an [appropriate model hook](https://github.com/jeremyevans/sequel/blob/master/doc/model_hooks.rdoc): https://github.com/cyberark/conjur/blob/3df4a7c86d14ddf85eed982efa74f953f3de88fd/app/models/credentials.rb
