### ISSUE TITLE
Generate a new Release

### ISSUE THREAD

**Issue by jvanderhoof** [cyberark/conjur#1576]
Please complete the following tasks to release this project.

- [x] Check `master` branch build is currently green (fix if it is not).
- [x] Pull all remote changes locally (`git pull --rebase origin`).
- [x] Review the scope of changes to understand the version new version ([Semver Summary](https://semver.org/#summary))
- [x] Increment the `VERSION` file to the desire release number.
- [x] Create a release branch (ex. `git checkout -b v1.2.3`) with the desired release number.
- [x] Review commits to insure all relevant changes have Changelog entries.
- [x] Review the `Gemfile.lock` history and update `NOTICES.txt` with any library changes.
- [x] Review `CHANGELOG.md` to:
  - [x] Move `Unreleased` changes to the release number.
  - [x] Refactor changes to confirm to the [Keep a Changelog Standard](https://keepachangelog.com/en/1.0.0/#how).
- [x] Open a Pull Request, tagging relevant teammates.
- [x] Upon approval and successful build, merge using "Squash and merge".
- [x] Tag the release (`git tag -a v1.2.3 -m "v1.2.3 release"` and `git push origin v1.2.3`).
- [x] Create a release branch at the point of the tag (`git fetch --all --tags`, `git checkout tags/v1.2.3 -b v1.2.3`, `git push origin v1.2.3`).
- [x] Wait for successful build.
- [ ] Add the Jenkins artifact name as a comment to this task.

**Comment by izgeri** [comment]
@jvanderhoof is this done? I checked off the items I know have been completed

also, is there a source of truth / template for this checklist? I think we need to add some smoke tests to it - we've had multiple failed releases recently (1.5.1 didn't publish to dockerhub, 1.6.0 broke the quick start, 1.7.0 broke a simple docker-compose environment in the buildpack)

**Comment by izgeri** [comment]
Debian artifact of release build is `conjur-possum_1.7.0.2-fadf83cc_amd64.deb`

Closing this issue now.
