### ISSUE TITLE
Multiple XFF headers not correctly handled

### ISSUE THREAD

**Issue by alexkalish** [cyberark/conjur#1583]
This was reported to support by professional services on behalf of DAP customer:

> In a scenario where we need XFF headers for CIDR restrictions, SSL offloading is required on the LB so that the XFF header can be added to the packet.

> When multiple LBs are in the route, each LB adds the previous LBs address to the packet as an XFF header. When the packet is processed by DAP, we aren't traversing the chain of XFF headers, rather just looking at the XFF header added by the LB immediately upstream. This results in the wrong IP address being evaluated for the client request.

**Comment by JL7777** [comment]
@alexkalish is this still current based on the Epic changes that were put in?

**Comment by alexkalish** [comment]
@JL7777: I believe that this was fixed, but @micahlee should confirm.

**Comment by micahlee** [comment]
It looks like this issue was prior to the trusted proxies work. If so, then yes, this is fixed.
