### ISSUE TITLE
Release Conjur for 11.5 release

### ISSUE THREAD

**Issue by jvanderhoof** [cyberark/conjur#1586]
Please complete the following tasks to release this project.

- [x] Check `master` branch build is currently green (fix if it is not).
- [x] Pull all remote changes locally (`git pull --rebase origin`).
- [x] Review the scope of changes to understand the version new version ([Semver Summary](https://semver.org/#summary))
- [x] Increment the `VERSION` file to the desire release number.
- [x] Create a release branch (ex. `git checkout -b v1.2.3`) with the desired release number.
- [x] Review commits to insure all relevant changes have Changelog entries.
- [x] Review the `Gemfile.lock` history and update `NOTICES.txt` with any library changes.
- [x] Review `CHANGELOG.md` to:
  - [x] Move `Unreleased` changes to the release number.
  - [x] Refactor changes to confirm to the [Keep a Changelog Standard](https://keepachangelog.com/en/1.0.0/#how).
- [x] Commit and push changes
- [x] Open a Pull Request, tagging relevant teammates and the Product Owner.
- [x] Upon approval and successful build, merge using "Squash and merge".
- [x] Check out `master` and pull: `git checkout master && git pull --rebase origin`
- [x] Tag the release (`git tag -a v1.2.3 -m "v1.2.3 release"` and `git push origin v1.2.3`).
- [x] Wait for successful build.
- [ ] Add the Jenkins artifact name as a comment to this task.

**Comment by izgeri** [comment]
@jvanderhoof fwiw I just tagged [v1.7.1](https://github.com/cyberark/conjur/releases/v1.7.1)

deb artifact: conjur-possum_1.7.1.1-898b9219_amd64.deb

**Comment by h-artzi** [comment]
Releasing new version

**Comment by h-artzi** [comment]
conjur-possum_1.7.2.0-bafdb3ac_amd64.deb

**Comment by h-artzi** [comment]
conjur-possum_1.7.2.1-e336a1d6_amd64.deb

**Comment by jtuttle** [comment]
Another release had to back out FIPS changes and add capabilities to release from a branch. New artifact is: `conjur-possum_1.7.4.0-b801923_amd64.deb`
