### ISSUE TITLE
Release Conjur for 11.6

### ISSUE THREAD

**Issue by sjacobs146** [cyberark/conjur#1660]
Please complete the following tasks to release this project.

### Create Release Branch

- [x] Checkout the git commit to release using its hash (`git co b5c271e1`).
- [x] Create a release branch (ex. `git checkout -b release/11.6`) from the
      commit with the PAS release number.
- [x] Push the release branch (`git push -u origin release/11.6`).
- [x] Check that the `release/11.6` branch build is currently green (fix if it
      is not).

### Update Release Artifacts

- [x] Review commits to ensure all relevant changes have Changelog entries. This
      may be accomplished using the `[Unreleased]` diff link in the CHANGELOG.
- [x] Share the final changelog in Slack (`#conjur-core`) with a proposed version for the release, based on the scope of changes ([Semver Summary](https://semver.org/#summary)), and ask for feedback and approval.
- [x] Once the new version number is approved by the Product Owner and/or Engineering Manager, increment the `VERSION` file to the desired release number.

- [x] Review the `Gemfile.lock` history and update `NOTICES.txt` with any library changes.

- [x] Review `CHANGELOG.md` to:
  - [x] Move `Unreleased` changes to the release number and delete any unused headers.
  - [x] Refactor changes to confirm to the [Keep a Changelog Standard](https://keepachangelog.com/en/1.0.0/#how).
  - [x] Add the following sections under `Unreleased`:
    <details><summary>View sections</summary>
      <p>### Added</p>
      <p>### Changed</p>
      <p>### Deprecated</p>
      <p>### Removed</p>
      <p>### Fixed</p>
      <p>### Security</p>
    </details>
- [x] Commit and push changes

- [x] Notify relevant teammates and the Product Owner to review the branch changes
      using a GitHub branch diff link (e.g. `https://github.com/cyberark/conjur/compare/release/11.6`).

- [x] Upon approval and successful build, tag the release
      (`git tag -a v1.2.3 -m "v1.2.3 release"`).
- [x] Push the tag (`git push origin v1.2.3`).
- [x] Wait for successful build.
- [x] Add the debian package name from the Jenkins build artifacts as a comment
      to this issue (e.g. `conjur-possum_1.7.4.0-b8019232_amd64.deb`). This can
      be found under **Build Artifacts** on the Jenkins build page.

### Re-integrate the Release Branch

- [x] Ensure the local release branch is up-to-date
      (`git checkout release/11.6` and `git pull`).
- [x] Create a new branch to integrate into master (`git checkout -v integrate-11.6`)
- [x] Rebase `integrate-11.6` on `master` (`git rebase origin/master`)
  - [ ] Resolve any conflicts as-needed with:

        ```
        # Resolve desired state in conflicted files and add stage them
        $ git add ...
        $ git rebase --continue

        # or if resolving the conflicts leads to no change on `master` then
        $ git rebase --skip
        ```

- [x] Open a Pull Request for `integrate-11.6` into `master`, tagging relevant
      teammates.
- [x] Upon approval and successful build, merge using "Squash and merge".

**Comment by micahlee** [comment]
Debian package: `conjur-possum_1.8.0.0-a93b9cf9_amd64.deb`

From: https://jenkins.conjur.net/job/cyberark--conjur/job/v1.8.0/

**Comment by h-artzi** [comment]
Debian package: conjur-possum_1.8.1.0-f1021336_amd64.deb
From: https://jenkins.conjur.net/blue/organizations/jenkins/cyberark--conjur/detail/v1.8.1/4/pipeline/260
