### ISSUE TITLE
CIDR Support Proxy - Refactor Origin IP Address Validation - Implementation 

### ISSUE THREAD

**Issue by nessiLahav** [cyberark/conjur#1662]
Refactor the code to be able support new proxy validation for authn authenticator and other in the future
As part fo the refactor, auth authenticator will align to the command class pattern.

DoD:
- [x] authn authenticator is aligned with the command class pattern
- [x] Implementation + UT

- [ ] Add validate proxy logic in authentication flow
- [ ] Add validate proxy method in auth authentication
- [ ] Implementation + UT according to the design

**Comment by Tovli** [comment]
We found out that we already implemented similar feature using evoke proxy to set the trusted proxies
This will be closed
