### ISSUE TITLE
CIDR support proxy - Enhance logs and supportability

### ISSUE THREAD

**Issue by nessiLahav** [cyberark/conjur#1666]
Add all the logs which mentioned in the solution design, 
and go over the flow to validate if more logs are necessary 

**DoD**

- [ ] Validate all the valid/invalid flows are explained trough the logs 

- [ ]  the logs messages reviewed by TW

**Comment by Tovli** [comment]
We have decided to go with https://github.com/cyberark/dap-wiki/pull/87 to provide both CIDR support and audits with right client ip in case of multiple proxies.
