### ISSUE TITLE
CIDR support proxy - Implement integration tests 

### ISSUE THREAD

**Issue by nessiLahav** [cyberark/conjur#1668]
Implement all integration tests with OSS env according to [test plan ](https://ca-il-confluence.il.cyber-ark.com/display/rndp/CIDR+Proxy+support+-+Test+plan)

DoD:

- [ ] Integration tests reviewed by QA

**Comment by Tovli** [comment]
We found out that we already implemented similar feature using evoke proxy to set the trusted proxies
This will be closed
