### ISSUE TITLE
Refactor IAM Authenticator to align with CommandClass Pattern

### ISSUE THREAD

**Issue by eranha** [cyberark/conjur#1677]
Most authenticators are using the [CommandClass] (https://github.com/jonahx/command_class) pattern, IAM authenticator is not one of them.

### DoD
- [ ] [CommandClass] (https://github.com/jonahx/command_class) pattern applied on IAM authenticator.
- [ ] Code reviewed and approved.
- [ ] Unit tests are passing.
- [ ] Integration tests are passing.

**Comment by Tovli** [comment]
We found out that we already implemented similar feature using evoke proxy to set the trusted proxies
This will be closed
