### ISSUE TITLE
A .NET client library is available for Conjur

### ISSUE THREAD

**Issue by InbalZilberman** [cyberark/conjur#171]
GIVEN I'm a .Net developer 
WHEN I develop an app
THEN I should be able to retrieve secrets I have permission using the Conjur .Net library

Conjur v4 has a .Net API that wraps the REST API of Conjur.

In V5 the API has been changed in an uncompatible way.

Your task, if you wish to accept it, is  to create a new .Net API compatible to v5 givving out the same functionality.

Please pay attention to the following:

1. Update the READ ME file and mention there:

A. Where can one fine usage example

B. What version on this API supports

2. Test coverage - should be the same as before

3. Understand if this can be part of the CE Github projects

**Comment by jvanderhoof** [comment]
Moved to the client project: https://github.com/cyberark/conjur-api-dotnet/issues/2
