### ISSUE TITLE
Test and Document the `X-Request-Id` header

### ISSUE THREAD

**Issue by micahlee** [cyberark/conjur#1714]
Conjur includes [middleware](https://github.com/cyberark/conjur/blob/master/lib/rack/remember_uuid.rb) for maintaining a well-known ID across API requests that will display in the audit log. This behavior is not tested or documented though.

DoD:
- [x] Tests exist to demonstrate and verify the behavior of the `x-request-id` HTTP header.
- [x] The behavior of `x-request-id` is documented in DAP wiki.
- [ ] An issue exists to document this behavior in the official docs.

See also: https://api.rubyonrails.org/classes/ActionDispatch/RequestId.html

**Comment by h-artzi** [comment]
https://github.com/cyberark/conjur-docs/issues/1333

https://github.com/cyberark/conjur/pull/1994

https://github.com/cyberark/dap-wiki/pull/159
