### ISSUE TITLE
Include `::1` in the default trusted proxies list

### ISSUE THREAD

**Issue by micahlee** [cyberark/conjur#1728]
Follow-up to https://github.com/cyberark/conjur/issues/1725

This issue is to consider whether to include the ipv6 `::1` address in the list of always trusted IPs for Conjur.

**Comment by alexkalish** [comment]
@micahlee: Thanks for taking the initiative with this, but I would prefer we just close the issue (pull it from the epic) and not merge the PR.  I don't want to complicate the release, even if the risk is very low.
