### ISSUE TITLE
Release Conjur for 11.7

### ISSUE THREAD

**Issue by sjacobs146** [cyberark/conjur#1767]
Please complete the following tasks to release this project.

### Create Release Branch

- [x] Checkout the git commit to release using its hash (`git co b5c271e1`).
- [x] Create a release branch (ex. `git checkout -b release/11.7`) from the
      commit with the PAS release number.
- [x] Push the release branch (`git push -u origin release/11.7`).
- [x] Check that the `release/11.7` branch build is currently green (fix if it
      is not).

### Update Release Artifacts

- [x] Review commits to ensure all relevant changes have Changelog entries. This
      may be accomplished using the `[Unreleased]` diff link in the CHANGELOG.
- [x] Share the final changelog in Slack (`#conjur-core`) with a proposed version
      for the release, based on the scope of changes ([Semver Summary](https://semver.org/#summary)),
      and ask for feedback and approval.
- [x] Once the new version number is approved by the Product Owner and/or
      Engineering Manager, increment the `VERSION` file to the desired release number.
- [x] Review the `Gemfile.lock` history and update `NOTICES.txt` with any library changes.
- [x] Review `CHANGELOG.md` to:
  - [x] Move `Unreleased` changes to the release number and delete any unused headers.
  - [x] Refactor changes to confirm to the [Keep a Changelog Standard](https://keepachangelog.com/en/1.0.0/#how).
  - [x] Add the following sections under `Unreleased`:
    <details><summary>View sections</summary>
      <p>### Added</p>
      <p>### Changed</p>
      <p>### Deprecated</p>
      <p>### Removed</p>
      <p>### Fixed</p>
      <p>### Security</p>
    </details>
- [x] Commit and push changes

- [x] Notify relevant teammates and the Product Owner to review the branch changes
      using a GitHub branch diff link (e.g. `https://github.com/cyberark/conjur/compare/release/11.7`).
- [x] Upon approval and successful build, tag the release
      (`git tag -a v1.2.3 -m "v1.2.3 release"`).
- [x] Push the tag (`git push origin v1.2.3`).
- [x] Wait for successful build.
- [x] Add the debian package name from the Jenkins build artifacts as a comment
      to this issue (e.g. `conjur-possum_1.7.4.0-b8019232_amd64.deb`). This can
      be found under **Build Artifacts** on the Jenkins build page.

### Re-integrate the Release Branch

- [x] Ensure the local release branch is up-to-date
      (`git checkout release/11.7` and `git pull`).
- [x] Create a new branch to integrate into master (`git checkout -v integrate-11.7`)
- [x] Rebase `integrate-11.7` on `master` (`git rebase origin/master`)
  - [x] Resolve any conflicts as-needed with:

        ```
        # Resolve desired state in conflicted files and add stage them
        $ git add ...
        $ git rebase --continue

        # or if resolving the conflicts leads to no change on `master` then
        $ git rebase --skip
        ```

- [ ] Open a Pull Request for `integrate-11.7` into `master`, tagging relevant
      teammates.
- [ ] Upon approval and successful build, merge using "Squash and merge".

**Comment by micahlee** [comment]
I don't see the `i18n` gem in our NOTICES file now, but the only change for 11.7 is an upgrade of that gem from `1.8.2` to `1.8.3`, which does include a license change.
