### ISSUE TITLE
All "possum" mentions have been renamed to "conjur"

### ISSUE THREAD

**Issue by brikelly** [cyberark/conjur#182]
"Possum" is the codename, but "Conjur" is the product name. This story requires that all instances of "possum" in the code/docs should be removed in favor of "conjur" (or "Conjur" depending on context).

**Comment by ryanprior** [comment]
@jtuttle renamed user-facing Possum references to Conjur. Some more internal references to "possum" remain, eg branch names, but those do not block launch so I consider this issue to be resolved and we should open other issues as necessary to rename other things.
