### ISSUE TITLE
There is a blog post describing using authn-k8s using annotation-based identities

### ISSUE THREAD

**Issue by diverdane** [cyberark/conjur#1854]
## Is your feature request related to a problem? Please describe.

A blog post describing:
- How authn-k8s works (e.g. workflow)
- How to deploy applications that use authn-k8s
would be very helpful to community members that are interested in using Kubernetes authentication.

## Describe the solution you would like

A blog post exists that covers the description above.

**Comment by izgeri** [comment]
It lives! https://www.conjur.org/blog/securing-secrets-in-kubernetes/
