### ISSUE TITLE
Rename `kubectl` to `kubeClient` across the code

### ISSUE THREAD

**Issue by abrahamko** [cyberark/conjur#1855]
Currently our code mentions many times the `kubectl` as a k8s client.
Although it is correct that `kubectl` **is** a k8s client, this is not the client we use in our code.
[kubectl](https://kubernetes.io/docs/reference/kubectl/kubectl/) is a k8s client used as a command-line tool and written in `go`.
We connect to k8s using a ruby gem called [kubeclient](https://github.com/abonas/kubeclient), which is a privately developed client that is unrelated to `kubectl`.

To prevent misunderstanding, we better replace all occurrences of `kubectl` with `kubeClient`.

**Comment by orenbm** [comment]
Thanks @abrahamko .

Just a small correction - the occurrences of `kubectl` in our code does does use the ruby gem (in these cases we actually call the object `kube_client`). In these cases we use a websocket to communicate with the K8s API.

How would you distinguish between the two?

**Comment by abrahamko** [comment]
> Thanks @abrahamko .
> 
> Just a small correction - the occurrences of `kubectl` in our code does does use the ruby gem (in these cases we actually call the object `kube_client`). In these cases we use a websocket to communicate with the K8s API.
> 
> How would you distinguish between the two?

So you actually don't use a client, so you can drop the `client`.
I would call it `k8s_exec` or `kube_exec`.
The fact that it uses websocket is an implementation detail, so it souldn't be in the class name.
