### ISSUE TITLE
database error after backup and restore

### ISSUE THREAD

**Issue by h-artzi** [cyberark/conjur#1948]
## Summary
Receive a 500 internal error while updating my policy [after a backup and restore](https://discuss.cyberarkcommons.org/t/database-error-after-backup-restore/474/11). 

## Steps to Reproduce
[Steps to Reproduce](https://discuss.cyberarkcommons.org/t/database-error-after-backup-restore/474/6)

## Expected Results
Update the policy accordingly

## Actual Results (including error logs, if applicable)
500 internal error

## Reproducible
   * [x] Always 
   * [ ] Sometimes
   * [ ] Non-Reproducible
   

## Environment setup
In a container

**Comment by izgeri** [comment]
hey @h-artzi - we don't have backup and restore for OSS, so is there a situation where this is reproducible using OSS only? if you could add repro details for OSS, it would be really helpful - I'm trying to understand this problem, but so far I've only seen it talked about in terms of DAP.

**Comment by micahlee** [comment]
@izgeri, we don't have an application-level backup restore for OSS, but we had the best repro steps for this from a CyberArk Commons discussion of backing up and restoring the Postgres database that Conjur OSS uses:
https://discuss.cyberarkcommons.org/t/database-error-after-backup-restore/474
