### ISSUE TITLE
Cannot access to zenhub

### ISSUE THREAD

**Issue by oburstein-hub** [cyberark/conjur#1960]
## Summary
Cannot access to zenhub

## Steps to Reproduce
1. Go to zenhub
2. Click on  task
3. getting "Something went wrong
An internal error happened"

## Expected Results
Task should open

## Actual Results (including error logs, if applicable)
getting "Something went wrong
An internal error happened"

## Reproducible
   * [+ ] Always 
   * [ ] Sometimes
   * [ ] Non-Reproducible
   
## Version/Tag number
What version of the product are you running? Any version info that you can share is helpful. 
For example, you might give the version from Docker logs, the Docker tag, a specific download URL, 
the output of the `/info` route, etc.

## Environment setup
Can you describe the environment in which this product is running? Is it running on a VM / in a container / in a cloud? 
Which cloud provider? Which container orchestrator (including version)? 
The more info you can share about your runtime environment, the better we may be able to reproduce the issue.

**Comment by izgeri** [comment]
@oburstein-hub this isn't a bug in Conjur, so I'm closing this issue now.
