### ISSUE TITLE
Change error message in retrieve variable if variable is empty

### ISSUE THREAD

**Issue by InbalZilberman** [cyberark/conjur#2023]
As a developer, I want to understand the different reasons for failing to retrieve a Conjur variable  , so that I can identify the problem better and resolve the it if needed.

Today when one retrieve a variable and the variable is empty he gets 
Variable <x> not found in account <y>
We would like to change only the message to
Variable <x> is empty or not found

GIVEN policy with variable X loaded
WHEN retrieving variable x
THEN return 404 with error message Variable <x> is empty or not found

## Developer Notes
- http code should remain the same
- code error in the message should remain the same

**Comment by InbalZilberman** [comment]
@alexkalish @izgeri FYI
@liavyona  please let me know if you need developer notes added

**Comment by liavyona** [comment]
@InbalZilberman @shulifink @izgeri @alexkalish is the message `Variable is empty or not found` should be on both cases? I think yes (security wise - we don't want to expose whether a secret exists or not)

**Comment by shulifink** [comment]
not sure about security issues etc, but the English is fine.

**Comment by InbalZilberman** [comment]
@liavyona what is the status of this bug?
Is there a PR that is linked to it?

**Comment by sashaCher** [comment]
@liavyona Role that has `execute` permissions on the variable can see that the variable is empty (exactly as it can see the variable value).

**Comment by InbalZilberman** [comment]
@sashaCher I think the remark you made should be addressed to @shulifink who asked if this is a security issue

**Comment by shulifink** [comment]
@sashaCher @InbalZilberman  - I was not asking about the security issue.
I was just saying that the english is fine and that I don't know anything about what in in brackets... but the english is fine. If everyone else is happy with what @liavyona  wrote in brackets, the I am too. :)

**Comment by InbalZilberman** [comment]
@liavyona all approved we can go on
