### ISSUE TITLE
HTTP API for public SSL certificate

### ISSUE THREAD

**Issue by alexkalish** [cyberark/conjur#2026]
## Functional User Story

**As a** Kubernetes operator 
**I want** an HTTPS REST API for fetching the Conjur node’s public SSL certificate 
**So that** I can easily and programmatically fetch it when configuring a K8s cluster

### Additional Details

* This will definitely require approval/review by a security architect.
* Please practice README-driven UX, so that PO + team can review before implementation.

**Comment by izgeri** [comment]
The dev team landed on different strategies for retrieving the Conjur SSL certificate programmatically: see #2038. As these will be implemented in cyberark/conjur-authn-k8s-client#232, I am closing this card now.
