### ISSUE TITLE
Helm chart for namespace Conjur configuration

### ISSUE THREAD

**Issue by alexkalish** [cyberark/conjur#2028]
## User Story

**As a** Kubernetes operator 
**I want** a Helm chart for creating Conjur resources and configuration specific an individual namespace   
**So that** I can easily prepare a namespace for Conjur client app. 

### Additional Details

* This should not duplicate any configuration stored centrally for the whole cluster. 
* Please practice README-driven UX, so that PO + team can review before implementation.

## Implementation/Solution Notes

**Comment by izgeri** [comment]
Closing, as this has moved to cyberark/conjur-authn-k8s-client#236
