### ISSUE TITLE
Audit log for WhoAmI request

### ISSUE THREAD

**Issue by netacoral** [cyberark/conjur#2052]
## Describe the solution you would like

I would like to add an enhancement to the audit log - create a log when using the WhoAmI request. The new log should have the following fields (example using JSON structure, but same fields should apply to syslog)

```
{
  "subject@43868": {
    "role": "demo:user:admin"
  },
  "auth@43868": {
    "user": "demo:user:admin"
  },
  "action@43868": {
    "result": "success",
    "operation": "check"
  },
  "PROGRAM": "conjur",
  "PID": "3490bfd0-75d1-4969-ac74-49ab3c48fc0d",
  "MSGID": "identity-check",
  "MESSAGE": "demo:user:admin checked their identity using WhoAmI",
  "LEVEL": "info",
  "ISODATE": "2020-04-15T15:56:53.771+00:00",
  "FACILITY": "auth"
}
```

**Comment by netacoral** [comment]
@alexkalish could you please review?

**Comment by amosmintzcyberark** [comment]
example json after review:

{
    "subject@43868": {
        "role": "CyberArk:user:admin"
    },
    "client@43868": {
        "ip": "172.17.0.1"
    },
    "auth@43868": {
        "user": "CyberArk:user:admin"
    },
    "action@43868": {
        "result": "success",
        "operation": "check"
    },
    "PROGRAM": "conjur",
    "PID": "8a5b09aa-532a-49ce-9c62-b0c503d8903a",
    "MSGID": "identity-check",
    "MESSAGE": "CyberArk:user:admin checked identity using WhoAmI",
    "LEVEL": "info",
    "ISODATE": "2021-03-07T16:00:39.625+00:00",
    "FACILITY": "auth"
}
