### ISSUE TITLE
Inconsistent behaviour with secret batch request with blank items

### ISSUE THREAD

**Issue by liavyona** [cyberark/conjur#2083]
## Summary
When sending the following request: `/secrets?variable_ids=,,,,,,,,` -> `422`
but when sending the following request: `/secrets?variable_ids=var1,,,,,,,,var2` -> `404`.

## Steps to Reproduce
1. authenticate
2. send the requests mentioned above

## Expected Results
Both cases to return the same error code. 

## Actual Results (including error logs, if applicable)
Each one returns different error code.

## Reproducible
   * [x] Always 
   * [ ] Sometimes
   * [ ] Non-Reproducible

**Comment by micahlee** [comment]
Closed by https://github.com/cyberark/conjur/pull/2074
