### ISSUE TITLE
Create file to track matching OpenAPI version and document updating it on releases

### ISSUE THREAD

**Issue by izgeri** [cyberark/conjur#2086]
- [x] Add an API_VERSION file to Conjur that has the spec version
- [x] Update Conjur releasing instructions to release the spec first and to make sure the Conjur Spec API_VERSION matches the API on the server in the release
- [x] Remove the SERVER_VERSION from the spec project

**Comment by izgeri** [comment]
@telday is this done? maybe this issue should replace the PR reference in the changelog?

**Comment by telday** [comment]
@izgeri It is finished, I must have overlooked this when making changes to both repos. Just opened a PR to update the changelog which should also close this issue.
