### ISSUE TITLE
Overloaded policy_versions table cause out of memory error

### ISSUE THREAD

**Issue by eranha** [cyberark/conjur#2298]

**Comment by InbalZilberman** [comment]
@eranha Thank you for this detailed explanation! Few comments:
1. Can you please fill in Expected Results and Actual Results sections?
2. Can you please name each solution and provide advantages and disadvantages?
2. Can you please explain what will be the user experience of the suggested solutions? 
3. I believe we spoke about a configuration to set the number of version history Conjur holds, can this be a third solution?
4. in 1.1 you wrote 1.1 Alter the list API to query only the names of the policies from resources
Alter from what? what happens today?
