### ISSUE TITLE
Links in 1.13.0 release

### ISSUE THREAD

**Issue by ryanprior** [cyberark/conjur#2351]
The JWT features added in 1.13.0 link to an internal portal, eg https://ca-il-jira.il.cyber-ark.com:8443/browse/ONYX-10520
Are these documented somewhere public?

**Comment by doodlesbykumbi** [comment]
Hey @ryanprior. Thanks for filing the issue. To the best of my knowledge there is no public alternative to that link, I've raised this internally and will update the issue as I know more. I don't think the release should be referencing non-public links.

**Comment by doodlesbykumbi** [comment]
Hey @ryanprior. Great to hear from you. Thanks for filing the issue. To the best of my knowledge there is no public alternative to that link, I've raised this internally and will update the issue as I know more. I don't think the release should be referencing non-public links.

**Comment by doodlesbykumbi** [comment]
@ryanprior This has been resolved by https://github.com/cyberark/conjur/pull/2362. Moving forward CHANGELOG entries should link to public issues where possible, otherwise to pull requests.
