### ISSUE TITLE
Enable GCP authenticator is not supported in authenticator API

### ISSUE THREAD

**Issue by aloncarmel111** [cyberark/conjur#2389]
## Is your feature request related to a problem? Please describe.
Cannot enable GCP authenticator using the authenticator API, the authenticator endpoint is not supporting  authenticator that doesn't  have service-id. 

## Describe the solution you would like

change the service-id to be optional parameter in the API endpoint 

## Additional context
The authenticator new API will update accordingly 

**URL:**

    `/:authenticator/(:service_id - optional parameter)/:account`

    Example: `/authn-k8s/my-authenticator/my-company`
    Example: `/authn-gcp/my-company`

* **Method:**

    `PATCH`

* **URL Parameters:**

  * `:authenticator`: The authenticator type (e.g. `authn-k8s`, `authn-oidc`).
  * `:service_id`: The name of the authenticator from the policy (`!webservice <service_id>`) - this is optional param.
  * `:account`: The Conjur account in which to enable this authenticator.

* **Request Content Type:**

    `application/x-www-form-urlencoded`

* **Body:**

    The Authenticator patch endpoint takes a single parameter, `enabled`, which
    may be set to either `true` to enable the authenticator (add it to the whitelist)
    or `false` to disable the authenticator (remove it from the whitelist).

**Comment by micahlee** [comment]
Hey @aloncarmel111 , is this issue closed by #2448 or is there more work to do?
