### ISSUE TITLE
Not an Issue - Conjur GUI

### ISSUE THREAD

**Issue by moedawood** [cyberark/conjur#2478]
Hi All

Is the conjur gui available on the open source version of the conjur ?

If so how would I enable it ? or is it enabled by default with the dockerfile ?

**Comment by szh** [comment]
Hi @moedawood,
Currently only Conjur Enterprise has an [Administrative Web UI](https://docs.cyberark.com/Product-Doc/OnlineHelp/AAM-DAP/Latest/en/Content/Operations/ui_intro_and_procedures.htm). You can see more information about the differences between Conjur OSS and Conjur Enterprise [here](https://docs.cyberark.com/Product-Doc/OnlineHelp/AAM-DAP/Latest/en/Content/Get%20Started/Enterprise_vs_OpenSource.htm).
