### ISSUE TITLE
unable to access the UI in open source setup, 

### ISSUE THREAD

**Issue by oahmed208** [cyberark/conjur#2568]
response="$(curl -d "{38p2qmm2y4tzhe2q82s3p1hgbyft6n5tje3y02vf4390ab1s3ng6pyw}" --cacert nginx.crt https://{172.20.43.246:8080}/authn/{admin}/{admin}/authenticate)"

this is the command I am running to access the token.

can I see the UI in an open-source version?

**Comment by szh** [comment]
Hi,
The Conjur UI is only available on Conjur Enterprise.
