### ISSUE TITLE
`Welcome` tab is highlighted when a user is on the `Get Started` section

### ISSUE THREAD

**Issue by jvanderhoof** [cyberark/conjur#259]
When a user is on the `get-started` section (http://localhost:4000/get-started/), the `Welcome` tab is still highlighted as active.  It should not be highlighted.  

Please see the attached screen shot for reference.

<img width="815" alt="screen shot 2017-08-16 at 6 57 37 am" src="https://user-images.githubusercontent.com/124978/29364724-aef746a6-8251-11e7-9420-2203b3f09fe2.png">

**Comment by jtuttle** [comment]
Looks good!
