### ISSUE TITLE
Dockerhub pull fails because of no `latest` tag

### ISSUE THREAD

**Issue by jvanderhoof** [cyberark/conjur#278]
When you try to pull from dockerhub:
```sh
$ docker pull cyberark/conjur
```
Docker responses with: 
```
Using default tag: latest
Error response from daemon: manifest for cyberark/conjur:latest not found
```
We need to add a `latest` tag to insure the above works.

**Comment by dustinmm80** [comment]
We need all 3 registries to act the same way here:

image names:
- `registry.tld/cyberark/conjur` - internal registry, private
- `cyberark/conjur` - dockerhub, public
- `quay.io/cyberark/conjur` - quay, public

**Comment by dustinmm80** [comment]
Branch and push strategy:

Images will be identified by their 3-digit semver version + the short SHA of their git commit.

Example: `cyberark/conjur:0.9.0-cadb209`.

With the semver and SHA in the version we can trace these artifacts easily through our systems.

**Comment by dustinmm80** [comment]
From the master branch, we will also apply the `latest` tag. `stable` is now redundant, we don't need it anymore.

Example: 
- `cyberark/conjur:0.9.0-1de94e9`, tagged as described above.
- `cyberark/conjur:latest`, we need `latest` so `docker pull cyberark/conjur` works.

Sticking to source control helps us here. Fewer moving parts, less confusion.

**Comment by dustinmm80** [comment]
Finally, for future releases like `0.9.1` we can manually tag these through our CI system. These releases will need to have release notes and doc updates - very similar to v4 releases, end to end. So an explicit manual promotion step is good for us here. Jenkins pipeline accommodate this with the `input` step.

**Comment by dustinmm80** [comment]
I think we should err towards being open about our builds, so I recommend we implement the above and evaluate it for a week or so. Thoughts before I start?

**Comment by jvanderhoof** [comment]
I like the `sha` addition.  Are  you thinking we push ALL images to our internal repository and final releases to all three?  I'd be hesitant pushing non-versioned releases to quay & dockerhub.

**Comment by apotterri** [comment]
Seems good to me. It's possible that we'll also want a tag like `0.9-latest` so folks can automatically pick up patches.

**Comment by dustinmm80** [comment]
Good point. Would you mind creating a separate issue for that Alan? I'd like to set it up as described and then enhance it w/ ideas like yours.

**Comment by apotterri** [comment]
https://github.com/cyberark/conjur/issues/279
