### ISSUE TITLE
Conjur CE Images tagged to ensure an easy pull for minor releases

### ISSUE THREAD

**Issue by apotterri** [cyberark/conjur#279]
As a consumer of the Conjur CE image, I want an easy way to control which image pull from a registry.

For example, being able to pull cyberark/conjur:latest to get the latest code is great. But, sometimes I'd like to stay at a minor release, and only pull patches. Having a tag like `1.1-latest` applied would enable me to pick up any patches applied to version `1.1`.

Given a version `1.1.1` (from `VERSION` file), in the Jenkins pipeline, let's create and push three different Conjur tags: 
- `cyberark/conjur:1`
- `cyberark/conjur:1.1`
- `cyberark/conjur:1.1.1`

This will allow users to choose the desired version level.

**Comment by ryanprior** [comment]
I confirmed here that this issue has not been resolved:

https://hub.docker.com/r/cyberark/conjur/tags/

Do we still want to update to use this strategy? Or has this become unimportant?
