### ISSUE TITLE
The doc site is reachable via www.conjur.org and conjur.org

### ISSUE THREAD

**Issue by brikelly** [cyberark/conjur#299]
try.conjur.org will eventually be retired but should still remain active.

**Comment by brikelly** [comment]
All 3 domains (www, try, and bare) should point to the same origin.

**Comment by ryanprior** [comment]
I confirm this works as of today. I believe @dustinmm80 did the work.

**Comment by dustinmm80** [comment]
I did indeed, thanks for closing this.
