### ISSUE TITLE
Integration pages should exist for launch integrations

### ISSUE THREAD

**Issue by dustinmm80** [cyberark/conjur#308]
We need to have a top-level sidebar nav called "Integrations".

For each integration we're releasing imminently, there should be a page in "Integrations" in this format and order:

- Name of integration
- Paragraph explaining integration
- Link to GitHub repo
- Links to tutorials relevant to the integration

**Comment by typaulhus** [comment]
I have an initial implementation of this, currently only linking directly to GitHub repos while we build out the pages and tutorials. 

Integrations:
- Ansible
- Go
- Java
- .NET
- Puppet
- Ruby
- Summon

**Comment by jtuttle** [comment]
I'm going to go ahead and fill out these landing pages.
