### ISSUE TITLE
AWS CloudFormation template has a quick-start guide

### ISSUE THREAD

**Issue by ryanprior** [cyberark/conjur#317]
The CloudFormation quick-start fills a gap between our two current options: self-hosted and CyberArk hosted Eval. It deserves a guide of similar clarity and brevity to help users get up and running in their own AWS cloud.

GIVEN I read the CloudFormation quick-start,
WHEN I follow the steps,
THEN I have a running Conjur server running in my own cloud
AND I am instructed on how to connect to it with the `cli5` container.

**Comment by jvanderhoof** [comment]
This issue was moved to cyberark/conjur-org#271
