### ISSUE TITLE
Issue with conjur install

### ISSUE THREAD

**Issue by ssk7317** [cyberark/conjur#419]
Team

I am trying to install conjur on a ubuntu machine on my environment using the steps mentioned in – https://www.conjur.org/get-started/install-conjur.html 

I am getting stuck in this step. IT is not able to start the conjur_1 container because of issues with Conjur_Data_key. Can you please help.

 

I am getting following error

conjur:/docker$ sudo docker-compose up conjur
docker_database_1 is up-to-date
Creating docker_conjur_1
Attaching to docker_conjur_1
conjur_1    | rake aborted!
conjur_1    | No CONJUR_DATA_KEY
conjur_1    | /opt/conjur-server/config/initializers/authenticator.rb:22:in `<top (required)>'
conjur_1    | /var/lib/gems/2.2.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:268:in `load'
conjur_1    | /var/lib/gems/2.2.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:268:in `block in load'
conjur_1    | /var/lib/gems/2.2.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:240:in `load_dependency'
conjur_1    | /var/lib/gems/2.2.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:268:in `load'
conjur_1    | /var/lib/gems/2.2.0/gems/railties-4.2.8/lib/rails/engine.rb:652:in `block in load_config_initializer'
conjur_1    | /var/lib/gems/2.2.0/gems/activesupport-4.2.8/lib/active_support/notifications.rb:166:in `instrument'
conjur_1    | /var/lib/gems/2.2.0/gems/railties-4.2.8/lib/rails/engine.rb:651:in `load_config_initializer'
conjur_1    | /var/lib/gems/2.2.0/gems/railties-4.2.8/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
conjur_1    | /var/lib/gems/2.2.0/gems/railties-4.2.8/lib/rails/engine.rb:615:in `each'
conjur_1    | /var/lib/gems/2.2.0/gems/railties-4.2.8/lib/rails/engine.rb:615:in `block in <class:Engine>'
conjur_1    | /var/lib/gems/2.2.0/gems/railties-4.2.8/lib/rails/initializable.rb:30:in `instance_exec'
conjur_1    | /var/lib/gems/2.2.0/gems/railties-4.2.8/lib/rails/initializable.rb:30:in `run'
conjur_1    | /var/lib/gems/2.2.0/gems/railties-4.2.8/lib/rails/initializable.rb:55:in `block in run_initializers'
conjur_1    | /var/lib/gems/2.2.0/gems/railties-4.2.8/lib/rails/initializable.rb:44:in `each'
conjur_1    | /var/lib/gems/2.2.0/gems/railties-4.2.8/lib/rails/initializable.rb:44:in `tsort_each_child'
conjur_1    | /var/lib/gems/2.2.0/gems/railties-4.2.8/lib/rails/initializable.rb:54:in `run_initializers'
conjur_1    | /var/lib/gems/2.2.0/gems/railties-4.2.8/lib/rails/application.rb:352:in `initialize!'
conjur_1    | /opt/conjur-server/config/environment.rb:5:in `<top (required)>'
conjur_1    | /var/lib/gems/2.2.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
conjur_1    | /var/lib/gems/2.2.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `block in require'
conjur_1    | /var/lib/gems/2.2.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:240:in `load_dependency'
conjur_1    | /var/lib/gems/2.2.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
conjur_1    | /var/lib/gems/2.2.0/gems/railties-4.2.8/lib/rails/application.rb:328:in `require_environment!'
conjur_1    | /var/lib/gems/2.2.0/gems/railties-4.2.8/lib/rails/application.rb:457:in `block in run_tasks_blocks'
conjur_1    | /var/lib/gems/2.2.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
conjur_1    | Tasks: TOP => db:migrate => db:migrate:load => environment
conjur_1    | (See full trace by running task with --trace)
conjur_1    | error: exit
docker_conjur_1 exited with code 1

**Comment by doodlesbykumbi** [comment]
@ssk7317 Before running `docker-compose up` you have to `Generate your master data key and load it into the environment:`

See below: 

![image](https://user-images.githubusercontent.com/8653164/31396457-574e914c-addb-11e7-9a39-4ff6412e1661.png)

**Comment by ssk7317** [comment]
@doodlesbykumbi 

I did these steps that are mentioned. I can see the data_key in the environment, but somehow conjur_1 container doesnt see that.

**Comment by doodlesbykumbi** [comment]
@ssk7317 

```
export CONJUR_DATA_KEY="$(< data_key)"
```

As best I know, the command above together with the `CONJUR_DATA_KEY` entry at `env:` in the `docker-compose.yml` should ensure that the `CONJUR_DATA_KEY` is available to `docker-compose up -d`

**Comment by ssk7317** [comment]
Thanks @doodlesbykumbi. Docker-console.yml was missing value in the conjur_data_key attribute. I updated that with the key and it works like magic.

But now I am wondering, if there is a better way to do it. Keeping Data_key in clear text in a config file.

**Comment by doodlesbykumbi** [comment]
@ssk7317 Not knowing which `docker-compose.yml` you're using, I'd like to suggest using the `docker-compose.yml` mentioned at https://www.conjur.org/get-started/install-conjur.html#prepare-to-launch.

Also available here: https://github.com/cyberark/conjur/blob/f7c94d9d548f8712e01ed3ac050bcd37dc9094c2/docs/get-started/docker-compose.quickstart.yml#L6-L13

With regard to keeping `CONJUR_DATA_KEY` in clear text in the `docker-compose.yml`, you don't need to do that! The link above show that `CONJUR_DATA_KEY:` is present (in the docker compose file) but empty. This is the convention used in docker compose files in order to pass environment variables from your shell to `docker-compose`. For additional information see https://docs.docker.com/compose/environment-variables/#passing-environment-variables-through-to-containers. 

I'm going to go ahead and close this issue now :)
