### ISSUE TITLE
Packages dependent on nokogiri updated

### ISSUE THREAD

**Issue by izgeri** [cyberark/conjur#427]
Older versions of nokogiri (before 1.8.1) have been found to be vulnerable to attack:
sparklemotion/nokogiri#1673
https://groups.google.com/forum/#!topic/ruby-security-ann/VZtBohEQ2iI

Conjur has been updated to use the newest version, but it still includes packages dependent on nokogiri that use an older version. These packages include:
html-proofer
loofah
rails-dom-testing

These packages should be updated to their most recent versions to fully patch this potential vulnerability.

As of last week,

The current version of html-proofer (3.7.3) uses nokogiri v1.7
The current version of loofah (2.1.1) uses nokogiri v1.5.9
The current version of rails-dom-testing (2.0.3) uses nokogiri v1.6

So none of them are updated to use nokogiri v1.8.1.

**Comment by jvanderhoof** [comment]
Resolved
