### ISSUE TITLE
Installation page on possum site needs more detail

### ISSUE THREAD

**Issue by dustinmm80** [cyberark/conjur#43]
https://possum-www.itci.conjur.net/installation/

Right now it just links out to two other pages, but it really should be more filled out and explain briefly what the difference between 'server' and 'client' are. An architecture diagram would be helpful here.

Screenshot:

<img width="956" alt="screen shot 2017-06-20 at 1 36 29 pm" src="https://user-images.githubusercontent.com/684459/27349618-87b99910-55bd-11e7-8501-a59127f9c8e9.png">

**Comment by mizziness** [comment]
Out of date, pages were changed and updated.
