### ISSUE TITLE
Should the quickstart text on cpanel be a link to the docs instead?

### ISSUE THREAD

**Issue by dustinmm80** [cyberark/conjur#44]
Screenshot:

<img width="819" alt="screen shot 2017-06-20 at 1 39 53 pm" src="https://user-images.githubusercontent.com/684459/27349769-f8cf545a-55bd-11e7-8128-47b51a03177a.png">

There is some helper text though, but it doesn't really get you very far. Logged into the Conjur CLI in an ephemeral container. What if we linked to the quick tour on the possum site instead? That way we could change them independently too.

**Comment by jvanderhoof** [comment]
This issue was moved to cyberark/conjur-org#272
