### ISSUE TITLE
Conjur.org Homepage Features (> "Integrations") break at 768px

### ISSUE THREAD

**Issue by mizziness** [cyberark/conjur#461]
In some tablet and mobile widths, the disparate heights of the boxes cause floats to display improperly: 

![image](https://user-images.githubusercontent.com/4164335/31900685-4876e0b8-b7ed-11e7-8017-b6f01f36f769.png)

**Comment by sigalsax** [comment]
As an aside, I found problem is stemming from:
.page{
font-family: 'Open Sans', sans-serif;
font-size: 16px;
}
.col-xs-1…{
padding-left: 15px;
padding-right: 15px;
body {
font-family- ‘Open Sans', sans-serif;
}
if the above are removed, issue is resolved and "Integrations" is in-line with "Built for Containers"

**Comment by jvanderhoof** [comment]
This issue was moved to cyberark/conjur-org#286
