### ISSUE TITLE
docker-compose.quickstart.yml missing port mapping referenced in the tutorials

### ISSUE THREAD

**Issue by dataplex** [cyberark/conjur#474]
The conjur.org installation quickstart guide (https://www.conjur.org/get-started/install-conjur.html) makes reference to using port 3000 to view the status page. However, the docker-compose.quickstart.yml (https://www.conjur.org/get-started/docker-compose.quickstart.yml) file downloaded is missing the port mapping for the conjur server container.

**Comment by ryanprior** [comment]
Thank you for the report @dataplex!

**Comment by jvanderhoof** [comment]
To close the loop, this change maps the Conjur container port to 8080. This allows Conjur to be available at: `http://localhost:8080`.
