### ISSUE TITLE
LDAP Authentication

### ISSUE THREAD

**Issue by jvanderhoof** [cyberark/conjur#524]
**Feature Overview**
LDAP authentication allows a user to authenticate with Conjur using credentials stored in a remote LDAP source rather than their Conjur credentials. LDAP authentication works exactly as regular authentication, returning a JSON hash if the user authenticates successfully.

**Workflow**
To enable the authenticator, the `CONJUR_AUTHENTICATORS` environment variable must be set on any Conjur node that may be servicing the authentication request, and it must include the string `authn-ldap/<authenticator-name>` in its comma-separated list of allowed authenticators (for example, `CONJUR_AUTHENTICATORS=authn-iam/aws,authn-ldap/o365`).

The authenticator webservice must be declared in Conjur policy:
```yml
- !policy
  id: conjur/authn-ldap/<authenticator-name>
  body:
  - !webservice

  - !group clients
 
  - !permit
    role: !group clients
    privilege: [ read, authenticate ]
    resource: !webservice
```
and the `clients` group can be used to entitle a user(s) to use the authenticator:
```yml
- !grant
  role: !group conjur/authn-ldap/<authenticator-name>/clients
  member: !user <username>
```

Once the authenticator has been properly configured, a user will be able to configure their environment to use LDAP authorization through the the Conjur CLI client, UI, or when using Summon by setting the `CONJUR_AUTHN_URL` environment variable:
```
CONJUR_AUTHN_URL = https://conjur.company.com/authn-ldap/<authenticator-name>/<service-account>/<username>/authenticate
```

To successfully use the LDAP authenticator to authenticate to Conjur (if entitled to do so in Conjur policy), a user needs their Conjur User ID to match their LDAP username.

**Implementation Details**
The authenticator itself is a class `AuthnLdap` in `lib/authenticators`. It has an `authenticate` method that returns true if the username and password match LDAP, and otherwise returns false.
```
  def authenticate(username, password)
```

The core routes will be updated to include
```
post ':authenticator/:service_id(/:account)/:login/authenticate' => 'authenticate#authenticate'
```

The core [`AuthenticateController`](https://github.com/cyberark/conjur/blob/master/app/controllers/authenticate_controller.rb) will be updated to define a `validate_security_requirements` method:
```
  def validate_security_requirements service_id, user_id
    security_requirements.validate(service_id, user_id)
  end

  def security_requirements
    AuthenticatorSecurity.new(
      authn_type: @authn_type,
      account: @account,
      whitelisted_authenticators: ENV['CONJUR_AUTHENTICATORS']
    )
  end
```
and its `authenticate` method must be updated to query the custom authenticator instead of the standard authenticator when there is another authenticator in the request path. In addition, it must be checked that the custom authenticator meets the security standards, so this might look something like:
```
  case params[:authenticator]
    when 'authn_ldap'
      validate_security_requirements service_id, username
      AuthnLdap.new.authenticate(username, password)
    else
      conjur_login(username, password)
    end
```

**Comment by izgeri** [comment]
@jvanderhoof - In the note about CONJUR_AUTHN_URL, where do they set it to use it with the UI? I am not sure that's a thing. Otherwise, to use it with the CLI or with the client libraries/Summon, they just need to set it on the machine / process running the calls.

**Comment by izgeri** [comment]
[Relevant WIP PR](https://github.com/cyberark/conjur/pull/522)

**Comment by jonahx** [comment]
@jvanderhoof 

Here's a method that will allow us to avoid any controller updates (actually, any code updates, period) when adding a new authenticator.

Instead, you'll just _add_ a new class to `lib/authenticators/<your authenticator name>`.

For example, to add an authenticator enabled by setting

```
CONJUR_AUTHENTICATORS=auth-my-cool-authenticator/some-service-id
```

You would create the file `lib/authenticators/my_cool_authenticator/authn.rb` with the following contents

```ruby
module Authenticators
  module MyCoolAuthenticator

    class Authn
      # this single method is the authenticator interface
      def valid?(login, password)
        # your authenticator logic
      end
    end

   end
end
```

Note the standard naming conventions:

1. Authenticator name in the url is kebab-case
2. Authenticator path name in lib snake_case, per rails convention
3. Authenticator module name is PascalCase

The controller logic will use ruby introspection on the `Authenticators` module to check if an `Authn` implementation is available for the authenticator specified in the route.

**Comment by izgeri** [comment]
@jonahx it would be worth noting what in the original post should be superceded by the comment above, to prevent confusion. But I like your idea!

**Comment by jonahx** [comment]
@izgeri Only the stuff under implementation details.  Which was only there initially to get us rolling and provide clarification of the concept.

**Comment by jvanderhoof** [comment]
This issue was closed with the following PRs:

- https://github.com/cyberark/conjur/pull/543
- https://github.com/cyberark/conjur/pull/541
- https://github.com/cyberark/conjur/pull/535
- https://github.com/cyberark/conjur/pull/522
