### ISSUE TITLE
Page TOC would be better as a floating sidebar on the right

### ISSUE THREAD

**Issue by dustinmm80** [cyberark/conjur#55]
For example, the TOC/prerequisites are taking up all the space above the fold for the Quick Tour

<img width="836" alt="screen shot 2017-06-20 at 2 16 41 pm" src="https://user-images.githubusercontent.com/684459/27351493-2d630608-55c3-11e7-8d3e-68c9069cf43b.png">

Instead, I think we should have a floating right sidebar for the page TOC, like on our current devsite. The TOC can move with the page, so it's always easy to navigate. This also removes the need for a 'back to top' button.

[CLI page on devsite](https://developer.conjur.net/cli), for example:

<img width="1049" alt="screen shot 2017-06-20 at 2 18 02 pm" src="https://user-images.githubusercontent.com/684459/27351571-7148f832-55c3-11e7-9d60-69cb315e35f3.png">

**Comment by mizziness** [comment]
No longer applicable
