### ISSUE TITLE
Conjur-eval doesn't work on Windows

### ISSUE THREAD

**Issue by UberKitten** [cyberark/conjur#550]
I tried running through the [Try Conjur](https://www.conjur.org/get-started/try-conjur.html) page on Windows 10 with Docker CE, but I ran into several issues.

The conjur-eval docker-compose.yml mounts the current directory in Windows as the /root/ directory. So the .netrc and .conjurrc files are written to the current directory in Windows.

When you try to run any command after authenticating, you get the following error:

    C:\Users\t3hub3rk1tten\Downloads\conjur-eval>docker-compose run conjur list
    error: netrc (/root/.netrc) shouldn't be world-readable

This is because Docker for Windows cannot translate Windows ACLs to Linux ACLs, so it returns all files as permission 0755.

Here's what that looks like from the shell:

```
root@d878b1dcc002:~# ls -la
total 23
drwxr-xr-x 2 root root 4096 May 14 19:59 .
drwxr-xr-x 1 root root 4096 May 14 20:02 ..
drwxr-xr-x 2 root root    0 May 12 21:16 .cache
-rwxr-xr-x 1 root root  146 May 14 19:58 .conjurrc
-rwxr-xr-x 1 root root  117 May 14 19:59 .netrc
-rwxr-xr-x 1 root root 3444 May 14 19:58 conjur-your.email@yourcompany.com.pem
-rwxr-xr-x 1 root root  118 May 12 21:12 docker-compose.yml
root@d878b1dcc002:~# stat .netrc
  File: '.netrc'
  Size: 117             Blocks: 1          IO Block: 16384  regular file
Device: 3dh/61d Inode: 4503599627408512  Links: 1
Access: (0755/-rwxr-xr-x)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2018-05-14 19:59:04.917413000 +0000
Modify: 2018-05-14 19:59:07.573850800 +0000
Change: 2018-05-14 19:59:07.573850800 +0000
 Birth: -
```

The only way I could get it to run was by mounting /root/conjur-eval to . and letting my ~/. files live in the Docker image. IMO the permissions should be a warning, not an error, but there may be a better way to solve this.

This is minor, but the instruction: `$ account="your.email@yourcompany.com"` and `docker-compose run conjur init -u https://eval.conjur.org -a ${account}` don't work on CMD or PowerShell either but are easily avoided at least.

**Comment by sjacobs146** [comment]
This issue is almost 3 years old. Closing.
