### ISSUE TITLE
Resources search API count should return total count, rather than result set count

### ISSUE THREAD

**Issue by micahlee** [cyberark/conjur#558]
#### Description
Currently, the `limit` parameter for listing/searching resources is applied before the matching records are counted. So, if there are 5 total resources in Conjur:
- `/resources?count=true` will return `{ "count": 5 }`
- `/resources?count=true&limit=2` will return `{ "count": 2 }`

#### Expected Result
The count should return the number of matching records on the server, not the number that would be returned with the `limit` applied.
- `/resources?count=true` should return `{ "count": 5 }`
- `/resources?count=true&limit=2` should return `{ "count": 5 }`
    >`limit` should be ignored in a `count` request

**Comment by kgilpin** [comment]
Specifying both limit and count could well be considered an invalid input.

**Comment by sjacobs146** [comment]
This issue is almost 3 years old. Closing
