### ISSUE TITLE
Ruby API tutorial would be much easier with an example github project

### ISSUE THREAD

**Issue by dustinmm80** [cyberark/conjur#56]
https://possum-www.itci.conjur.net/tutorials/integrations/ruby.html

There is a lot of 'setup' in this tutorial, copy/pasting files, setting up possum environment. The time to value is too long IMO.

One solution is to have a github project that is linked with this tutorial (not sure on all the mechanics at this point). That way, someone can just clone the repo, run `docker-compose up -d`/similar, and get to work.

**Comment by jvanderhoof** [comment]
This issue was moved to cyberark/conjur-org#273
