### ISSUE TITLE
Failure to push to quay.io halts continuous delivery pipeline

### ISSUE THREAD

**Issue by ryanprior** [cyberark/conjur#598]
### Situation
Given that quay.io is having an outage and will sporadically return HTTP 500 errors,
And that you're simultaneously running Jenkins builds of Conjur,
When Jenkins tries to push to quay.io,
Then the 500 error will trigger a script failure and Jenkins will totally halt the continuous delivery pipeline.

### Example
https://jenkins.conjur.net/blue/organizations/jenkins/cyberark--conjur/detail/master/383/pipeline/

**Comment by kgilpin** [comment]
I don’t see how this is a bug. Isn’t it important that the Quay step succeed?

**Comment by izgeri** [comment]
We're removing quay in #1579, so I'm closing this issue now.
