### ISSUE TITLE
Custom authentication tutorial needs more specifics about accounts

### ISSUE THREAD

**Issue by apotterri** [cyberark/conjur#60]
The [custom authentication tutorial](https://possum-www.itci.conjur.net/tutorials/integrations/authenticators.html) kind of glosses over accounts. 

For example, It has a reference to an `account` variable here: 
<img width="297" alt="no-account" src="https://user-images.githubusercontent.com/4212483/27354242-e97a9a5c-55d4-11e7-813a-ffe2d7df1463.png">
but doesn't set it anywhere.

Later, in the [example](https://possum-www.itci.conjur.net/tutorials/integrations/authenticators.html#example), it uses an account of `myorg` in the request for a URL that it says should work. The request fails, though, because the account doesn't exist.

Finally, in [Client Configuration](https://possum-www.itci.conjur.net/tutorials/integrations/authenticators.html#client-configuration), `CONJUR_ACCOUNT` needs to be set before the Ruby REPL is started.

**Comment by jvanderhoof** [comment]
This issue was moved to cyberark/conjur-org#277
