### ISSUE TITLE
K8s authenticator only creates one CA per service

### ISSUE THREAD

**Issue by jonahx** [cyberark/conjur#716]
Bug:

 - change rake task to use Repos::ConjurCA
 - or put it into the authenticator, and move code in authenticate_controller
   to an initializer
 - I think Repos::ConjurCA can be used unchanged.  It’s just that you’ll only
   be using it once per webservice vs once per host.  You shouldn’t need to
   bring back AuthenticationService (I think)

**Comment by jtuttle** [comment]
PR: https://github.com/cyberark/conjur/pull/696
