### ISSUE TITLE
k8s inject_client_cert checks for authenticator

### ISSUE THREAD

**Issue by jtuttle** [cyberark/conjur#738]
The inject_client_cert path in the k8s authenticator currently does not use the `Strategy` object, which means it doesn't perform a check to ensure that the k8s authenticator is enabled. We should refactor the authenticator enabled check out of strategy and use it in the validation step for each authenticator.

**Comment by orenbm** [comment]
issue #1525 should resolve this

**Comment by orenbm** [comment]
Fixed by #1525
