### ISSUE TITLE
A failed rotation retries immediately

### ISSUE THREAD

**Issue by apotterri** [cyberark/conjur#741]
In an EE container, I patched the `conjur/possum` service to work around #740 and see why my rotation was failing. I found that a failed rotation is retried immediately and continuously.

**Comment by garkler** [comment]
@apotterri is this still critical in your mind? If so I would like to get it prioritized with PM

**Comment by apotterri** [comment]
After a Slack discussion about this, I was persuaded that this isn't actually a bug. It can be closed.

**Comment by andytinkham** [comment]
Closing bug per Alan's comment from February.
