### ISSUE TITLE
Creating a new host using hf token can cause an exception, depending on the name

### ISSUE THREAD

**Issue by ryanprior** [cyberark/conjur#744]
Creating a host called `brand-new-host` using an hf token causes an exception, while naming it `brand_new_host` works fine.

#### Steps to reproduce
1. login to Conjur as admin
1. load this policy as root:
   ```yaml
   - !policy
     id: database
     body:
       - !layer users
       - !host-factory
         id: users
         layers: [ !layer users ]
   ```
1. create a host factory token: `conjur hostfactory tokens create database/users`
1. use the token to create a host: `conjur hostfactory hosts create $token brand-new-host`

Expected result: new host created, id and API key returned
Actual result: 500 error

#### Workaround
If you instead create the host with id `brand_new_host`, you get the expected result.

#### Side note

With the request to create a new host, the Conjur CLI is sending some unfamiliar data. Examples:

```
__parent__[%23%3CGLI%3A%3ACommand%3A%3AParentKey%3A0x000000018bf6b8%3E]&id=brand-new-host
```

```
__parent__[%23%3CGLI%3A%3ACommand%3A%3AParentKey%3A0x00000002bd76b0%3E]&id=brand_new_host
```

All I'd expect to see is the last part, `id=whatever`. Why is there a ParentKey with some kind of pointer address or something in there?

#### Session log

```sh-session
$ conjur hostfactory tokens create database/users
[
  {
    "token": "[redacted]",
    "expiration": "2018-09-21T20:53:24+00:00",
    "cidr": [

    ]
  }
]
$ conjur hostfactory hosts create [redacted] "brand-new-host"
RestClient.post "https://eval.conjur.org/host_factories/hosts", "__parent__[%23%3CGLI%3A%3ACommand%3A%3AParentKey%3A0x000000018bf6b8%3E]&id=brand-new-host", "Accept"=>"*/*", "Accept-Encoding"=>"gzip, deflate", "Authorization"=>"Token token=\"1eydjya19ht5xd1tyyf5k8dm7me3gq3g5420nbxhdk84nyr1j5t1r\"", "Content-Length"=>"89", "Content-Type"=>"application/x-www-form-urlencoded", "User-Agent"=>"rest-client/2.0.2 (linux-gnu x86_64) ruby/2.4.1p111"
# => 500 InternalServerError | text/html 0 bytes

error: 500 Internal Server Error


$ conjur hostfactory hosts create [redacted] "brand_new_host"
RestClient.post "https://eval.conjur.org/host_factories/hosts", "__parent__[%23%3CGLI%3A%3ACommand%3A%3AParentKey%3A0x00000002bd76b0%3E]&id=brand_new_host", "Accept"=>"*/*", "Accept-Encoding"=>"gzip, deflate", "Authorization"=>"Token token=\"1eydjya19ht5xd1tyyf5k8dm7me3gq3g5420nbxhdk84nyr1j5t1r\"", "Content-Length"=>"89", "Content-Type"=>"application/x-www-form-urlencoded", "User-Agent"=>"rest-client/2.0.2 (linux-gnu x86_64) ruby/2.4.1p111"
# => 201 Created | application/json 261 bytes
{
  "created_at": "2018-09-21T19:53:56.525+00:00",
  "id": "ryan.prior@cyberark.com:host:brand_new_host",
  "owner": "ryan.prior@cyberark.com:host_factory:database/users",
  "permissions": [

  ],
  "annotations": [

  ],
  "api_key": "[redacted]"
}
```

**Comment by micahlee** [comment]
Hey @ryanprior, I'm having trouble reproducing these results. I have a couple of follow up questions that I'm hoping can help refine this for me:

- How are you executing the conjur CLI? Is this native on a host machine, running in docker, etc.?
- Which CLI version are you running via `conjur --version`?
- What are you using to print out the RestClient data showing the `__parent__...` data?

Thanks!
Micah

**Comment by micahlee** [comment]
Thanks Ryan! That's a help clarification. I'll check this again and begin fix shortly!

**Comment by micahlee** [comment]
@ryanprior, ok I wasn't able to get a reproducible automated test for this. The basic repro steps are:

1. Load policy for a host factory "A"
2. Create a token for host factory A
3. Create a host "my-host" with host factory A
4. Load a new policy REPLACING the existing policy for a host factory "B"
5. Create a token for host factory B
6. Create a host "my-host" with host factory B

The issue is that the policy replace deletes the Resource objects, but not the Roles from the initial policy load. So rather than a `403 forbidden` because host factory B doesn't have ownership of "my-host", there is a `500` response because Conjur can't find the resource associated with the existing role "my-host".

It looks like the correct behavior in this scenario would be the `403 forbidden` response. Do you agree?
