### ISSUE TITLE
Decouple `login` and `authenticate` strategies in the authenticator framework

### ISSUE THREAD

**Issue by micahlee** [cyberark/conjur#747]
Per @jonahx:
>Having this extra method on Strategy pushes me just to the edge (maybe over) of how far I like to stretch SRP. If I rewriting this today I'd use two command objects, perhaps ExchangeCredentialsForToken (previously Strategy) and ExchangeCredentialsForApiKey.

>All of the shared logic would be pulled out into objects, which both of them would delegate to: eg, ValidateSecurity, ValidateAuthenticatorExists, etc....

**Comment by orenbm** [comment]
@jonahx @micahlee i don't see any `Strategy` object in our code so I guess this issue is now irrelevant. I created this [issue](https://github.com/cyberark/conjur/issues/1525) that will properly do what is intended to happen in this issue.

Can we close this issue?

**Comment by micahlee** [comment]
Yeah, I think this was essentially resolved with: https://github.com/cyberark/conjur/commit/7a32e4b0b2e8226e32cdc6429281bfe290b95a9e#diff-725274190d26c047c07b492a8adcabd9

Closing, thanks!
