### ISSUE TITLE
Kubernetes authenticator setup supports multi-tenancy

### ISSUE THREAD

**Issue by jtuttle** [cyberark/conjur#759]
Configuring Conjur to use the k8s authenticator requires a [rake task](https://github.com/cyberark/conjur/blob/master/lib/tasks/authn_k8s.rake) to be run that expect the `CONJUR_ACCOUNT` environment variable to be set on the container. This doesn't make sense in a multi-tenancy environment because the container environment will not be tied to a single account.

As a quick fix, we could add an account parameter to the rake task instead of having it pull from the environment. In the future we should figure out a way to remove the rake task from the setup process.

**Comment by sjacobs146** [comment]
This issue is over 2  years old. Closing
