### ISSUE TITLE
Kubernetes authenticator assumes container name is "authenticator"

### ISSUE THREAD

**Issue by izgeri** [cyberark/conjur#762]
There appears to be a hardcoded assumption in the Kubernetes authenticator post-refactor that the container name will be "authenticator". Prior to the refactor, Secretless was deployed with the container name "secretless" and worked as expected; with 5.2.1 this no longer works.

It appears it's still comparing the container name to the `kubernetes/authentication-container-name` annotation, and failing if they don't match (which is good)

But it should not assume the value will be `authenticator`

Steps to reproduce:
- Deploy an authenticator where the `kubernetes/authentication-container-name` annotation in policy and the container name are both set to something besides `authenticator`
- Login fails because the cert can't be copied to the pod, and the Conjur logs (in debug logging mode, with the fix in #761 applied) show `Authentication Error: Cert could not be copied to pod: ["\"Websocket handshake error: :invalid_status_code\""]`

**Comment by jtuttle** [comment]
"authenticator" is used as the default value in [kubectl_exec](https://github.com/cyberark/conjur/blob/master/app/domain/authentication/authn_k8s/kubectl_exec.rb#L87) which is being instantiated (w/ the default value) in [inject_client_cert.rb](https://github.com/cyberark/conjur/blob/master/app/domain/authentication/authn_k8s/inject_client_cert.rb#L30).
