### ISSUE TITLE
Flapping GKE test

### ISSUE THREAD

**Issue by jvanderhoof** [cyberark/conjur#768]
We're seeing occasional failures with the following test:
cucumber ./cucumber/kubernetes/features/authenticate.feature:15 # Scenario: Authenticate as a Deployment.

For example: https://jenkins.conjur.net/blue/organizations/jenkins/cyberark--conjur/detail/master/477/pipeline

**Comment by orenbm** [comment]
@jvanderhoof seems that this is not flapping anymore. Can we close this issue?
