### ISSUE TITLE
Tests for Cluster have been evaluated

### ISSUE THREAD

**Issue by jvanderhoof** [cyberark/conjur#771]
Acceptance Criteria:

- [ ] Evaluate this Conjur component and write a complete test plan
- [ ] Evaluate the current test implementation for this component,
and document the items from the test plan that are not yet implemented
(please add to Summary doc so there is a single place to see an overview
of the statuses)

[Test plan template](https://cyberark365.sharepoint.com/:w:/s/Conjur/EfWSd_wkCmBJjULPrLGLQ8MBcYosIfaIyx4yzulDQs8QTw?e=WGu6BO) (copy and create a new file in the folder)

[Summary doc](https://cyberark365.sharepoint.com/:w:/s/Conjur/EXqW4lJCOcRFj2fzVGfYGV4B4ojeW3OTfm4troWIeW0Z9A?e=4D7f4B)

**Comment by izgeri** [comment]
Deprioritizing for now.
