### ISSUE TITLE
Code Climate has been added to critical repos

### ISSUE THREAD

**Issue by izgeri** [cyberark/conjur#786]
For all critical repos (which may reasonably be defined as any repo that has had a `swarm/testing` evaluation completed for it), add Code Climate auto-linting.

**Comment by izgeri** [comment]
@jvanderhoof this one is pretty big - maybe it should be `kind/epic` with stories for each repo underneath? lmk what you think.

**Comment by izgeri** [comment]
CC has been added to most repos in the [conjur suite](https://cyberark.github.io/conjur) (cc @andytinkham) - closing now.

**Comment by andytinkham** [comment]
I disagree with the justification - CC may be aware of most of the repos, but most don't have a .codeclimate.yml file meaning they're at best getting only the basic core scans and no language-specific linting (at least from CC). However, I agree with closing this issue, as I am no longer convinced that CC is the way we should be going for our linting. I don't yet have a better alternative, but I also don't think we should spend a lot of time/effort on increasing the scanning in the short term.
