### ISSUE TITLE
Add test for creating host factory token with params in request body

### ISSUE THREAD

**Issue by jtuttle** [cyberark/conjur#792]
A [recent pull request](https://github.com/cyberark/conjur/pull/772) disabled Conjur's usage of a Rails feature that [automatically copies body parameters](https://github.com/cyberark/conjur/pull/772/files#diff-b1fe55db50c712fef0673345e5b9c0d9R70) into the request URL params. This ended up breaking the host factory token creation endpoint.

We likely didn't catch this in the cukes because they're not encoding request parameters in the same manner as an API request. We should make sure the cukes are more faithful to what's actually happening to ensure test coverage.

**Comment by sgnn7** [comment]
More details:
Our cukes add query params to requests through the use of appended string to the URL itself which is processed differently then our CLI API calls which embed those qury parameters inside the body of the request itself. If the controller does not have the BodyParser added to it, this will make the cukes pass and CLI API calls fail so we need to ensure that our cukes use the body-embedded query parameters to test the exact functionality that our APIs will envoke.
