### ISSUE TITLE
PKI Service Generates Valid Certificates

### ISSUE THREAD

**Issue by micahlee** [cyberark/conjur#842]
More work needs to be done to validate that the certificates generated by the PKI/CA endpoints are valid.

Known AC:
- [ ] Certificate attribute values are within specified bounds [Link](https://tools.ietf.org/html/rfc5280#appendix-A.1)
- [ ] Certificate alt-names are valid (Need to verify, but the current certs probably fail to parse with the golang x509 libraries)

**Comment by sjacobs146** [comment]
This bug is over 2 years old. Closing.
