### ISSUE TITLE
Fix ADFS Certificate issue

### ISSUE THREAD

**Issue by moticless** [cyberark/conjur#924]
The provider certificate is supplied to conjur container. For some reason in case of ADFS certificate, the ssl negotiation  gets failed. With keycloak it succeeds
child of #838

**Comment by moticless** [comment]
childof #838

**Comment by nessiLahav** [comment]
We have an issue to validate ADFS self signed certificate:
https://security.stackexchange.com/questions/143061/does-openssl-refuse-self-signed-certificates-without-basic-constraints

As a solution we will replace the ADFS certificate to be signed by a CA
