### ISSUE TITLE
Return specific reason error description of Conjur Access Token expiration

### ISSUE THREAD

**Issue by nessiLahav** [cyberark/conjur#935]
Before This card:

- [x] Consult with PO if this change is necessary for auth-oidc use case

- [x] Consult with Conjur Senior developer if it could brake backward compatibility

- [x] Get approval from Security Architect  

Given I have a valid Conjur access token 
And token time expiration exceeded 
When I Access Conjur server

Actual: The error is “401 Unauthorized: Invalid token”
Expected:  Then the error should be “401 Unauthorized: Expired token”

Thread in Slack:
https://conjurhq.slack.com/archives/C9Y674APJ/p1556528198008800

child of #974

**Comment by jvanderhoof** [comment]
I don't love the bullet points at the beginning of the issue.  It makes it very hard to understand if this story is valid or not.  Would it be possible to either change the dashes to checkboxes so someone not directly involved knew the steps were complete, or move it to either the `selected` or `defining` columns and add details and decisions via comments?

**Comment by orenbm** [comment]
This issue is implemented
