### ISSUE TITLE
`rotate_api_key --user non-existing` in cli should print correct message

### ISSUE THREAD

**Issue by orenbm** [cyberark/conjur#979]
In the cli when you run the following command:
`rotate_api_key --user non-existing` 
the message is:
`Unable to authenticate with Conjur. Please check your credentials.`

the correct message should indicate that the user `non-existing` doesn't exist.

**Comment by eladkug** [comment]
@shaharglazner can we send message "user non-exisitng" from security perspective ?

**Comment by sashaCher** [comment]
There's no security aspect in writhing right message if `non-existing` user does not exist and user that runs `rotate_api_key` command is an authenticated user.
